### ISSUE TITLE
Which module provides CommentsConfig's dependencies?

### ISSUE THREAD

**Issue by akardapolov** [angryip/ipscan#103]
Hi!

Maybe offtop :) but anyway.. 
I can't find dependencies in ipscan code base for CommentsConfig class. 

public class DetailsWindow extends AbstractModalDialog {
	@Inject CommentsConfig commentsConfig;

https://github.com/angryip/ipscan/blob/7ebb4f6ae8b551f6f1477416c3aaed2ff6caaeee/src/net/azib/ipscan/config/CommentsConfig.java

My sample app using dagger 2.11 raise NPE without @Provides annotations on a similar case.

Thanks,
Alex.

**Comment by angryziber** [comment]
I guess it works because CommentsConfig has a constructor marked annotated with @Inject. If I remember correctly, dagger2 cannot inject unannotated classes, so you need to have an @Inject, even for a default constructor.

**Comment by akardapolov** [comment]
>> so you need to have an @Inject, even for a default constructor.

Well, I have but no result.
It seems I need to go deeper to Dagger 2 :)

Thank you!
