### ISSUE TITLE
Windows binary requires Java 1.7

### ISSUE THREAD

**Issue by BillT42** [angryip/ipscan#111]
Java is updated to 1.8, but windows binary insists on requiring v1.7, incidentally the installer looks for 1.6

**Comment by asier70** [comment]
Also java 9 is not recognized and application can't be run. I have only java 9 installed on windows.

**Comment by BillT42** [comment]
I have installed the old version of java in addition to the newer versions and it does run. But the java updater does want to delete the old version every time

 

Bill Timmins

**Comment by asier70** [comment]
I have the same experience like you, so java 9 support is desired.

**Comment by angryziber** [comment]
Fix for Java 9 released - 3.5.2, thanks
