### ISSUE TITLE
Java 9 (1.9) is not detected, Angry IP Scanner not working anymore

### ISSUE THREAD

**Issue by GoodSoulGermany** [angryip/ipscan#115]
After upgrading to Java 9 Angry IP Scanner stops working. It shows an errormessage complaining that I neede at least Java 1.7 (7).

**Comment by JEDtoo** [comment]
I have the same issue. I pulled the latest 3.5.1 amd64.deb and it won't install because I'm running 1.9.

**Comment by angryziber** [comment]
Fix released, thanks

**Comment by JEDtoo** [comment]
Thanks! The install works fine on by Ubuntu 16.04.3 now and the program runs.
