### ISSUE TITLE
Not Scanning IPs ending with .0

### ISSUE THREAD

**Issue by Raiser991** [angryip/ipscan#120]
Using: Windows 32-bit Executable from http://angryip.org/download/#windows

Scanning an IP-Range like 10.10.10.0 - 10.10.12.255 the software wont show IPs ending with .0 like 10.10.11.0 or 10.10.12.0.
See attached .png 
![ipscann](https://user-images.githubusercontent.com/34285111/33629136-50e0cc18-da03-11e7-8c1d-b2d60b4bdb6d.PNG)

**Comment by dpse** [comment]
IP addresses ending in 0 and 255 are skipped by default. You can change this in the preferences ("Tools" > "Preferences").

![image](https://user-images.githubusercontent.com/10079846/33706083-2a0107a8-db33-11e7-9ec8-b61f5d8126ed.png)

**Comment by angryziber** [comment]
Thanks, @dpse 
@Raiser991 - do you have anything listening on *.0 addresses? Or you asked just of curiousity?
