### ISSUE TITLE
Comments not displayed

### ISSUE THREAD

**Issue by Giochia** [angryip/ipscan#124]
Most comments are not displayed until a double click on the single cell is done.

**Comment by angryziber** [comment]
The comments are tied to the MAC address if it is available, and to the IP otherwise.
Can you provide more info/steps to better understand the issue?

**Comment by angryziber** [comment]
Finally I understand the issue: the bug is when MAC Fetcher is not before the Comments fetcher.
A fix is coming in 3.7.4
