### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by buffcode** [angryip/ipscan#129]
[According to the documentation](http://angryip.org/documentation/) internally IPv6 is already supported, just the UI is not ready yet.

It would be nice to support IPv6, as the addresses are quite difficult to remember... ;)

**Comment by stefan1983** [comment]
+1

**Comment by benediktneumayr** [comment]
*+1*

**Comment by Jatin328** [comment]
+1

**Comment by angryziber** [comment]
Latest versions support IPv6 in some way
