### ISSUE TITLE
The ICMP Echo ban

### ISSUE THREAD

**Issue by PorscheMonty** [angryip/ipscan#133]
Hello there.

First, thank you a lot for this excellent software; I love it. I've been using it forever and it has never failed to do it's job :)

Now, long story short, I managed to get full-blown raw socket functionality working in WinXP SP3, but AngryIP won't let me choose ICMP Echo irrespective of my system's inherent capacity to handle it.

The choice to deny the common XP user access to this better feature is perfectly understandable on obvious technical grounds, though I'd very greatly appreciate if something could be done so to allow for it to be used also on plain WinXP (I'm assuming it already works fine with 2003, which's said not to be affected by the limitation). It could be made available through a manual, direct modification of the config, thus avoiding conflicts for the rest of the XP world who has no need of it.

Thanks for your time and sorry for the inconveniences.

**Comment by angryziber** [comment]
I doubt the pinging using RAW sockets would be any better than using iphlpapi.dll, that is built into Windows.

Windows XP restrictions mostly interfere with number of parallel hosts that can be scanned, so if you got around the restrictions, just increase the number of parallel threads and enjoy :-)
