### ISSUE TITLE
Export scan option

### ISSUE THREAD

**Issue by Tarjei99** [angryip/ipscan#141]
Hi,

It would be very practical if the result of the scan could be exported to a delimited file. Ideally it would be nice to choose which delimiter to use, but comma would be excellent.

The reason for the delimited file is to read the data into a spreadsheet (Google, Excel, whatever) without any major surgery on the data.

Side note : I love the MAC vendor feature.

**Comment by angryziber** [comment]
You can already choose between different export file formats in export dialog - one of them is `Comma-separated file (csv)`
