### ISSUE TITLE
'Check for newer version...' falsely reports new version

### ISSUE THREAD

**Issue by stephenyeargin** [angryip/ipscan#142]
## Reproduction steps

1. Open the application
1. Menu > Angry IP Scanner > Check for newer version...
1. Observe that the "newest" version is listed as `<html>`
1. Download version and observe that it is the same version as installed

## Screenshot

![screen shot 2018-06-22 at 12 01 00 pm](https://user-images.githubusercontent.com/80459/41789396-c44a852e-7614-11e8-816e-eae0636399cb.png)

## Debugging

It appears that when the website was moved to GitHub Pages, SSL was enforced (which is good). However, the linked configuration still had the non-SSL link implemented, which would cause the request to receive a 302 header and the body shown below:

```
$ curl -i http://angryip.org/ipscan/IPSCAN.VERSION
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://angryip.org/ipscan/IPSCAN.VERSION
X-GitHub-Request-Id: 13F4:5B72:E82A3C:13521E8:5B2D2393
Content-Length: 178
Accept-Ranges: bytes
Date: Fri, 22 Jun 2018 17:05:58 GMT
Via: 1.1 varnish
Age: 2275
Connection: keep-alive
X-Served-By: cache-ewr18144-EWR
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1529687159.561428,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 32127a72c6f20bb7e33777424b62f1bbb345f822

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
``` 

The fix is likely to update the link shown here:

https://github.com/angryip/ipscan/blob/86e8327fa5c4445ded8b2a7465cdd796f239233d/src/net/azib/ipscan/config/Version.java#L20

Which is then used to build the link here:

https://github.com/angryip/ipscan/blob/86e8327fa5c4445ded8b2a7465cdd796f239233d/src/net/azib/ipscan/config/Version.java#L36

**Comment by angryziber** [comment]
Thanks for pointing this out. I have disabled automatic redirect to https for now, because old versions will still use http. However, Java URLConnection should follow redirects by default, so I need to investigate this a bit more

**Comment by angryziber** [comment]
OK, it seems Java URLConnection doesn't follow http->https redirects, but handles http->http just well
https://stackoverflow.com/questions/1884230/urlconnection-doesnt-follow-redirect

**Comment by stephenyeargin** [comment]
That's frustrating. I don't think GitHub Pages will let you have one URL available at a non-SSL link. I suppose the path forward would be to leave the SSL redirect disabled for a certain amount of time while releasing a new version with it fixed. After that time has passed, re-enable the SSL requirement in hopes folks will realize they need to upgrade.
