### ISSUE TITLE
Request: Monitor when a server has finished rebooting and RDP is available again

### ISSUE THREAD

**Issue by gatehead** [angryip/ipscan#148]
Hello,
I work on a few remote machines and quite often when I reboot them I need to run ping -t to find out when they're back up, but will have to wait for port 3389 to open before I can RDP back in. Times such as windows update will show a machine responding to ICMP but nothing on 3389, which leaves you testing a few times.

I would love if we could have a feature where I tag a server as rebooting, and angry IP scanner would work in the background checking ping then port 3389 then popup and let me know when the server is back online and ready for RDP.

Does this sound like a useful feature, an easy to implement feature and something worth adding?

Thanks

**Comment by angryziber** [comment]
It probably won't fit withe concept as is, but an idea would be to create a simple batch file that does pinging and port probing in a loop and register it as an opener in Angry IP Scanner that you could easily run for any machine
