### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Sh4d0wR00t85** [angryip/ipscan#150]
for some reason i cant seem to get the software installed.
i cant find the chmod commands for it nor anything else some help would be nice

**Comment by Sh4d0wR00t85** [comment]
the package from here and the OS is parrot
https://github.com/angryip/ipscan.git

**Comment by JonnyTech** [comment]
The installers are found on the [releases page](https://github.com/angryip/ipscan/releases).

Since "parrot" is based on debian, you need [the deb file](https://github.com/angryip/ipscan/releases/download/3.5.3/ipscan_3.5.3_amd64.deb) (I assume that you are running on a 64bit computer).

**Comment by Sh4d0wR00t85** [comment]
Yes I use that but nothing seems to want to cooperate with me lol 


Sent from Yahoo Mail for iPhone


On Tuesday, September 11, 2018, 12:57, JonnyTech <notifications@github.com> wrote:


The installers are found on the releases page.

Since "parrot" is based on debian, you need the deb file (I assume that you are running on a 64bit computer).

**Comment by Sh4d0wR00t85** [comment]
thing is none of the chmod commands work im still truely learning the ins and outs of the OS

**Comment by Sh4d0wR00t85** [comment]
well damn lol found it

**Comment by angryziber** [comment]
Ok, closing
