### ISSUE TITLE
false positives on OSX and no network names with shared network connection

### ISSUE THREAD

**Issue by fred-dev** [angryip/ipscan#154]
I have a very specific scenario, I am using the DHCP server inside OSX. I have a wifi connection to the internet (adapter address 192.168.1.1 but anything really), then I use internet sharing to share my connection from wifi to an ethernet adaptor (manual address 192.168.2.1). This sets the DHCP to give out addresses to devices connected to the ethernet connection addresses starting at 192.168.2.2. When I perform a scan starting at 192.168.2.2 to 192.168.2.254, I often get devices found with 0ms ping time for every possible address, often an active device shows no response, and I don't see any network names for any devices.

**Comment by rradillen** [comment]
I'm having exactly the same issue.

**Comment by angryziber** [comment]
Please try other pinging methods in preferences, most notably "Java Built-In". Does any of them work?
