### ISSUE TITLE
Mac Addresses of Different Vlans not showing

### ISSUE THREAD

**Issue by Letlaka** [angryip/ipscan#155]
The problem i have is that we have 8 VLANS and out of the 8 the only VLAN that shows me MAC addresses is the one i connected too. To get the other mac address of the other Vlans i need to connect to that Vlan and start the scan from there. Is there a way to scan all my VLANs and have the scanner show me mac addresses of all machines even those in different VLANS.

**Comment by angryziber** [comment]
Angry IP Scanner uses ARP protocol to discover the MAC, which obviously works only in the current LAN.
Outside of the LAN MAC address is not generally visible or routable. This is how networks work.

If you have Windows machines, they may expose their MAC over NetBIOS port, try NetBIOS fetcher on them.
