### ISSUE TITLE
false negatives in macOS

### ISSUE THREAD

**Issue by zippydan** [angryip/ipscan#158]
Running AngryIP Scanner 3.5.3
Running macOS 10.14 Mojave

MacBook Air 2014 on WiFi

A ping from macOS terminal gives me an immediate sub-10ms response from, say, 192.168.1.52 (which is another active PC on the same LAN).

I run a scan in Angry IP Scanner (on the same macOS computer) from 192.168.1.1 - 192.168.1.255.

I do show other hosts alive on the subnet, so the Angry IP Scanner is working to some degree, but 192.168.1.52 shows as a dead host (red dot with [n/a] for ping response).

The "dead" host is a Windows 8 machine.

Any further troubleshooting steps I can take?  Does Angry IP Scanner on macOS not use the built-in ping command?

I've used Angry IP Scanner for years on Windows with no complaints.  This is one of my first times trying it in macOS.

**Comment by angryziber** [comment]
Please try the new Java Built-In pinging method, it uses ICMP (as ping command), but only if it has permissions. Otherwise it tries connecting to TCP port 7.
