### ISSUE TITLE
Clicking on "Display: xxx" in status bar doesn't revert properly?

### ISSUE THREAD

**Issue by MagnusThome** [angryip/ipscan#161]
If I have the status bar setting set to "Display: All" first I see all hosts and if I then click on "Display: Open ports" I'll get only these host. All well so far.

But if I then click on "Display: All" the hosts that dissapeared on my previous click will not come back in the list. I still only see the ones that replied on ports.

**Comment by angryziber** [comment]
This is by design, because switching to "Display: Alive" will actually delete data on dead hosts and frees the memory. You can rescan if for some reason you want to get them back.
