### ISSUE TITLE
Comments no saving

### ISSUE THREAD

**Issue by khallamuk** [angryip/ipscan#163]
When I fill in comments they are only stored for that session - on close or re-scan all comments are gone

**Comment by angryziber** [comment]
Which OS? Are there any errors in console?

**Comment by khallamuk** [comment]
Hello

Its Windows 10 1803. There are no errors – everything works find its just the comments don’t appear to be saved

Kind regards,

Keith Hallam

**Comment by angryziber** [comment]
I have just checked on Windows 10 and it worked.
Note that for local IPs the comments are attached to the MAC address and for remote ones to the IP.

Please check what do you have in Registry:
HKEY_CURRENT_USER\Software\JavaSoft\Prefs\ipscan\comments

Do you see your comments there?

**Comment by khallamuk** [comment]
Hello,

There are a few entries but even these don’t show in the program.

I am running Angry on a VM if this makes any difference? All the machines are connected a Cisco switch and this is the only MAC that is displayed when scanning

Kind regards,

Keith Hallam

**Comment by angryziber** [comment]
Probably fixed in 3.8.2
