### ISSUE TITLE
3.5.4 Not pulling results

### ISSUE THREAD

**Issue by Runningwolf999** [angryip/ipscan#165]
Hi, I just downloaded and installed 3.5.4 and ran a scan on my network and did not pick up any devices at all.  Only question marks in the far left hand column beside IP addresses.
Java: Oracle Corporation 1.8.0_191-b12
OS: Windows 7 6.1 (amd64)

Also installed on another network on a Server and got the same results.
Java: Oracle Corporation 1.8.0_191-b12
OS: Windows Server 2016 10.0 (amd64)

**Comment by rificity** [comment]
Same here. Went back to 3.5.3 and it works again. (Windows 10 Home)

**Comment by angryziber** [comment]
Thanks guys, I remember testing for this, but probably tested a wrong binary. Will release fixed 3.5.5 shortly
