### ISSUE TITLE
Enabling the MAC address fetcher results in no alive hosts being scanned/reported (blank results) and regardless when working results are wildly inaccurate

### ISSUE THREAD

**Issue by CollinChaffin** [angryip/ipscan#173]
For me on Windows 7 x64 with any Java (8,10,11) angryip is 100% BROKEN if I simply enable the MAC address fetcher.  You would think this might depend on the type of scan selected in the tool be it ICMP.DLL, UDP, or TCP+UDP - it does NOT.  Regardless of ANY other setting, running with UAC totally disabled as full admin, it does not matter if the MAC address fetcher is pushed to the left "enabled" side of the list, all scanning functionality is lost.  Enable any/ALL other fetchers EXCEPT the MAC address, and the tool again works.

This was on a version 6 mo old all the way to today's latest available binary for 64bit Windows (v3.5.5).  Considering scanning with MAC address included is critical, I am very surprised this has not been flagged as more critical as I can easily reproduce on multiple Win7x64 machines.  I have not taken the time yet to perform testing on other versions such as Win10 so perhaps it is not impacting everyone since I do see issue #94 has been sitting without so much as an acknowledgement in the OPEN state, for coming up on TWO YEARS.  Perhaps @angryziber could at least acknowledge this as an issue in need of attention and if I get some time I can dig through the code and perhaps come up with a PR to get it resolved.

With that said, even if the above helps someone else I urge you to hold the phone and keep reading.  I just began capturing an actual video because I cannot explain how a still fairly simple ping/port scan tool can be this blatantly inaccurate, when it finally does (appear) to work.  I can scan 23 live hosts (with only the ping fetcher enabled) so surely it works now?  Wrong.  As an alternate, I download advanced ip scanner, open it, don't even set a single option and click scan and I get all THIRTY-SEVEN live hosts on my segment - not the TWENTY-THREE angry finds using ANY of the scan methods.  WTF?  I then open a simple command prompt and type `ping 192.168.1.149` and watch it ping, then go back and even narrow my angryip search to a SINGLE address of only that address, and still watch it tell me that host is dead when EVERY other scanner I try finds it (and all other 37 live hosts).  Clearly since v2 when I used it all the time something is just not working correctly in this scanner.  Again not my PC if it happens on multiple and only with this scanner and every other scanner works properly however this is the only one based on Java yet trying with various java versions also has not changed the result.

Without digging through the code if you happen to reply before I can dig is there a way to enable any kind of debug logging to be able to see what, from Java, is being executed and returned to be making the tool THIS inaccurate?  I really would like to help obviously or I would simply just ditched angryip all together.  TIA!

**Comment by angryziber** [comment]
Thanks for the report. Unfortunately, I cannot reproduce the problem on Windows 10.
MAC address fetcher on Windows uses SendARP API (http://msdn.microsoft.com/en-us/library/windows/desktop/aa366358(v=vs.85).aspx)

From your description it's not very clear what exactly is broken. Do you get all addresses as dead (red)? Or do you get "broken"/blank results, or anything else? A screenshot would be nice.

If you would like to help with debugging, please download a Java IDE, like Intellij IDEA or Eclipse, open the project source and put breakpoint in WinMACFetcher class to see what's happening there.
