### ISSUE TITLE
Why does it try to connect to contacts.google.com?

### ISSUE THREAD

**Issue by CameronTurner** [angryip/ipscan#177]
<img width="752" alt="screen shot 2019-01-16 at 11 53 01 pm" src="https://user-images.githubusercontent.com/10741654/51250313-195bd080-19ea-11e9-8e85-336cfc35ffce.png">

**Comment by Eyremba** [comment]
@CameronTurner you could answer the question by yourself by taking a closer look into the source code... therefore it is open-source.
 ipscan/src/net/azib/ipscan/util/GoogleAnalytics.java

**Comment by CameronTurner** [comment]
Thanks for the smart ass answer, 

So getting back to the question, the GoogleAnalytics.java file or any other aspect doesn't reference the contacts.google.com URI that I could find. Any further ideas on what is triggering a contacts.google request? Seems odd to hit that URL, I don't see any other apps using GA hitting that domain.

**Comment by unmec** [comment]
From the screenshot I guess you are using LittleSnitch.

If my memory is correct, it could be a dns cache issue. If you have a process A that made requests to contacts.google.com very recently, then when you launch process B that makes requests to analytics.google.com which happen to be resolved with a same IP address as contacts.google.com, LittleSnitch will prompt you with contacts.google.com.

However as suggested, it's always the best to take a closer look at the source when you have doubt.

**Comment by angryziber** [comment]
Thanks for the suggestion, @unmec - I was thinking the same.
Another possibility is some third-party fetcher, but this is even less likely.
Anyway, contacts.google.com is not something that Angry IP Scanner uses, and Google Analytics receives only anonymous crash and version check requests once per month.
