### ISSUE TITLE
Support for AdoptOpenJDK

### ISSUE THREAD

**Issue by Rouzax** [angryip/ipscan#179]
Will Angry IP scanner support AdoptOpenJDK from https://adoptopenjdk.net/ as runtime in the future?

**Comment by angryziber** [comment]
Sure, but which platform doesn't work currently?
And which version of OpenJDK?

**Comment by Rouzax** [comment]
Sorry that was a very lousy issue description on my part 👍 
OS: Windows 2019
JDK: OpenJDK JRE with Hotspot 8.0.202.8 (x64) (installed through https://ninite.com/)

it keeps telling me
![image](https://user-images.githubusercontent.com/4103090/53733009-e24d5b80-3e7f-11e9-8e99-e75d336a46eb.png)

**Comment by angryziber** [comment]
Maybe ninite installs Java to a non-standard location? Where your javaw.exe is located?
Angry IP Scanner uses http://launch4j.sourceforge.net/ for it's launcher on Windows.
Make sure you are using the latest Angry IP Scanner that was built using the latest Launch4J.

If the issue persists, the workaround is to launch Angry IP Scanner manually:
`path_to\javaw.exe -jar ipscan.exe`

**Comment by Rouzax** [comment]
First I only had the x64 AdoptOpenJDKi installed but that didn;t work when lauching from the command line.
after installin the x86 the location of javaw.exe is `C:\Program Files (x86)\AdoptOpenJDK\jdk8u202-b08-jre\bin`
Angry IP scan is version 3.5.5

When running `"C:\Program Files (x86)\AdoptOpenJDK\jdk8u202-b08-jre\bin\javaw.exe" -jar "C:\Program Files\Angry IP Scanner\ipscan.exe"` it works.

**Comment by angryziber** [comment]
Windows launcher was rewritten in 3.6.2 to use JAVA_HOME and PATH env variables, please test.

**Comment by Rouzax** [comment]
Sorry for the late reply but yes it works
