### ISSUE TITLE
Build 3.5.5 is missing librocksaw.so on 64 bit .deb

### ISSUE THREAD

**Issue by AlexApps99** [angryip/ipscan#181]
ICMP ping was not working on latest version, investigated and noticed that `librocksaw.so` was missing inside .jar file installed through `ipscan_3.5.5_amd64.deb`. Not sure if this problem also occurs in other builds, but I fixed it by finding `librocksaw.so` in source and adding it to the .jar file.
It's probably related to the new build system, just posting here so it can be fixed permanently.

- https://github.com/angryip/ipscan/releases/download/3.5.5/ipscan_3.5.5_amd64.deb
- https://github.com/angryip/ipscan/blob/master/ext/rocksaw/lib/linux64/librocksaw.so

**Comment by AlexApps99** [comment]
https://github.com/angryip/ipscan/commit/4446870efcf40b3be13d626454594e1369edc67a
This commit may have something to do with it... Unsure

**Comment by angryziber** [comment]
Yes, that was a mistake when switching to gradle, indeed. Thanks for pointing this out
