### ISSUE TITLE
Dark Mode For MacOS

### ISSUE THREAD

**Issue by thib5** [angryip/ipscan#182]
Hi, Since MacOS Mojave, Mac have a dark theme ... please make one for Angry ip !!!

**Comment by croaking** [comment]
please :)

**Comment by angryziber** [comment]
Hmm, isn't it something that is just provided by the OS?

**Comment by Zwilla** [comment]
will give the first kick today

**Comment by thib5** [comment]
Any news on that ?

**Comment by Tackyou** [comment]
![Screen Shot 2019-12-25 at 22 47 41](https://user-images.githubusercontent.com/4498638/71450762-93ebaf00-2768-11ea-9a28-ec2ef645fe96.png)
This is how it looks with dark mode currently. Can't read text ..

**Comment by torinnguyen** [comment]
Same for me
<img width="659" alt="Preferences 2020-02-24 20-41-18" src="https://user-images.githubusercontent.com/767320/75157144-1df2cc80-5746-11ea-8b5c-8bc4f95a28f7.png">

**Comment by taylorsduncan** [comment]
Boooooooo!

**Comment by OdysLam** [comment]
Hey everyone, 

Can we change to day-view for this particular app (while keeping the night system-wide)

**Comment by angryziber** [comment]
@torinnguyen did you do anything for the app to be displayed this way?
When I run it on Catalina in dark mode it just displays in light mode, because it wasn't linked with SDK 10.14. Or which version of Java do you use and how did you install it?

**Comment by angryziber** [comment]
You can also try playing with NSRequiresAquaSystemAppearance in Info.plist inside of the app bundle:
https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app

Or try the latest binary from here, does it show readable text?
https://github.com/angryip/ipscan/actions/runs/55669151

**Comment by angryziber** [comment]
@OdysLam  as a workaround you can use this trick to force light/dark mode of individual apps:
https://stackoverflow.com/questions/52562383/is-there-a-way-to-toggle-dark-mode-on-off-for-individual-apps-in-macos-mojave

Bundle id of Angry IP Scanner is `net.azib.ipscan`

**Comment by angryziber** [comment]
Dark mode is now supported and looks ok
You can test the build here:
https://github.com/angryip/ipscan/actions/runs/55787937

**Comment by OdysLam** [comment]
Hey @angryziber, dark mode looks awesome!!

Thanks :)
