### ISSUE TITLE
Application freezes when exporting

### ISSUE THREAD

**Issue by iloominaty** [angryip/ipscan#184]
Hi

When i try to export a scan the program will freeze and never recover.

What i do:
Scan the range from 10.2.2.0-10.2.2.255
If i press any of the export options the program will freeze permanently.

On macOS Mojave (10.14.4)

**Comment by suniversal** [comment]
I have the same issue in 10.14.3 - cannot export a scan, no matter the options/methods tried. Maybe a potential cups printing permissions issue... see multiple temp files in /var/spool/cups.

**Comment by PPourkhosravy** [comment]
Same here

**Comment by darryl-harper** [comment]
Same here on 10.14.5
plus here: https://sourceforge.net/p/ipscan/discussion/80382/thread/cef2ef5ac1/?limit=25 on 10.9.5 in 2005, so I'm not going to hold my breath waiting for a fix ;)

**Comment by angryziber** [comment]
Seems like being a mac-only issue. The export works perfectly on Linux.

Please let the app freeze and then execute `jstack` with the PID and paste the thread dump here that I can analyze.

**Comment by angryziber** [comment]
Another question: does the freeze occur before the save dialog is shown or after?
Does the file open dialog work?
How other apps behave?

May this be related: https://apple.stackexchange.com/questions/262072/file-open-dialog-freezing-on-macos-10-12

**Comment by angryziber** [comment]
Fixed in master, will be released as 3.6.1
