### ISSUE TITLE
Silent uninstall is not silent

### ISSUE THREAD

**Issue by cmolstad** [angryip/ipscan#185]
The following command is supposed to uninstall Angry IP Scanner silently:

"C:\Program Files\Angry IP Scanner\uninstall.exe" /S

However, this does not work and it still pops up a box asking if it should be uninstalled.

**Comment by kk04CyberMonk** [comment]
have you figured out the silent switch or any other way to uninstall this application silently ?

**Comment by cmolstad** [comment]
> 
> 
> have you figured out the silent switch or any other way to uninstall this application silently ?

No, /S still doesn't work as of version 3.5.5.  Haven't tried anything newer yet.

**Comment by angryziber** [comment]
Have you tried 3.7.0, which was built with updated NSIS?
