### ISSUE TITLE
Vendor LOOKUP

### ISSUE THREAD

**Issue by sjweinstein** [angryip/ipscan#188]
Vendor LOOK up always returns CISCO   I see the plugin  to add a resource file for IEEE vendors in linux  but i run on a Windows 10 system    Is ther a way to do this?

**Comment by angryziber** [comment]
Are the MAC addresses resolved correctly? Maybe your router always substitutes it's own MAC?
Angry IP Scanner does include an IEEE DB with vendor prefixes
