### ISSUE TITLE
Requires JRE 1.7.0 in Windows v3.5.5

### ISSUE THREAD

**Issue by Antzy** [angryip/ipscan#192]
I can see that there have been similar issues in the past and they have been fixed and closed. But I'm running a fresh install of windows and installed the latest JRE (Version 8 Update 211) and installed IP scanner v3.5.5. Am getting the error "This application requires a Java Runtime Environment 1.7.0". Have tried with the x32 and x64 exe, as well as the installer.

**Comment by icecore2** [comment]
Same here.

**Comment by angryziber** [comment]
Angry IP Scanner uses Launch4J to generate Windows exe files.
Can you please check if Lauch4J works on your machine?
http://launch4j.sourceforge.net/

**Comment by angryziber** [comment]
Windows launcher has been rewritten from scratch in 3.6.2, please test.
