### ISSUE TITLE
Illegal reflective access by net.azib.ipscan.fetchers.HostnameFetcher

### ISSUE THREAD

**Issue by waitnsea** [angryip/ipscan#197]
full output : 
$ ipscan
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.azib.ipscan.fetchers.HostnameFetcher (file:/usr/share/java/ipscan/ipscan-linux64-3.5.5.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of net.azib.ipscan.fetchers.HostnameFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ipscan  11,21s user 1,05s system 4% cpu 4:40,38 total

**Comment by angryziber** [comment]
Thanks, but this is normal for Java 9+

**Comment by angryziber** [comment]
We are using "illegal" access to improve hostname lookup performance and reliability

**Comment by stemar88** [comment]
┌─[✗]─[r3dp1ll@parrot]─[~]
└──╼ $ipscan
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.azib.ipscan.fetchers.HostnameFetcher (file:/usr/lib/ipscan/ipscan-linux64-3.5.5.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of net.azib.ipscan.fetchers.HostnameFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
