### ISSUE TITLE
Most inaccurate scanner I've used

### ISSUE THREAD

**Issue by CollinChaffin** [angryip/ipscan#198]
I really like the interface but I can my subnet with angry defaults, I get 19 hosts.  I increase the packets sent to an ungodly higher number, suddenly I get 31 hosts.  Fire up advanced ip scanner, nmap, and numerous others and straight out of the box they ALL detect all 33 hosts without any tweaking - a feat no matter what I can't even accomplish (or found a way) using angry scanner.  Even removing ALL fetchers except ping still does not improve the results to anywhere near accurate.

Note even a simple Powershell script or raw ICMP CMD script ALSO render 33 hosts, so there's no magic happening on my hosts to be filtering - IMO there simply MUST be some serious bugs in this code to never be able to even once get an accurate scan.  

Hopefully it can get addressed as in addition to liking the interface, I also like being able to select the fetchers.

**Comment by angryziber** [comment]
Are you using Windows?
Do you use Windows pinger or TCP/UDP in Preferences? Can you please test all of them?

**Comment by angryziber** [comment]
No additional info provides, so nothing to do here. The scanner works for me and many other users.
May be a machine or router issue.
