### ISSUE TITLE
Shows amd64 on a Intel system

### ISSUE THREAD

**Issue by gemal** [angryip/ipscan#205]
I'm version 3.6.1 on my Windows 10

![image](https://user-images.githubusercontent.com/69105/64941162-2c1ef180-d866-11e9-8cbc-6f37c578b6db.png)

it says amd64 but I'm on Intel

![image](https://user-images.githubusercontent.com/69105/64941244-5e305380-d866-11e9-82d2-0f49fd5bc570.png)

**Comment by angryziber** [comment]
This is how Java Virtual Machine designates a 64-bit x86 system, because
AMD was the first to introduce 64-bit x86 CPUs back in the day.
