### ISSUE TITLE
Why can an *.exe program run and be decompressed by a decompression program?

### ISSUE THREAD

**Issue by VKingi** [angryip/ipscan#207]
## A question that bothers me:
1. *.exe Programs can be run separately
1.1. No unzipped files were found during the run (SFX Support does not decompress?)
2. *.exe  can also be unzipped as a compressed file

> What is the principle of *.Exe?

**Comment by angryziber** [comment]
Angryip uses Launch4j, which adds an exe header to a Java jar file to be
executable under Windows (this exe header finds Java and passes the file to
it for execution). Java jar files are actually zip-compressed class files,
which are decompressed on the fly.

**Comment by VKingi** [comment]
@angryziber  Thank you for your answer.
