### ISSUE TITLE
no longer seeing MAC address or MAC vendor

### ISSUE THREAD

**Issue by Walt455** [angryip/ipscan#209]
Since I have done the update, I am no longer able to see the MAC address or MAC vendor. Any ideas why?

**Comment by angryziber** [comment]
Which version of Angry IP Scanner?
Which operating system?

**Comment by KayRJay** [comment]
I am running 3.6.2 on MacOS Mojave 10.14.6.  Same issue.

**Comment by Giochia** [comment]
Same issue. My version is 3.6.2 running on UBUNTU 18.04.4 LTS

**Comment by pjockey** [comment]
Same. 3.7.0 on MX-Linux 19.1

**Comment by angryziber** [comment]
Works for me in Ubuntu

Do you have `arp` command-line tool installed?
What do you see by running `arp` shortly after the scan?

**Comment by Giochia** [comment]
Just updated to Version 3.7.2, still no MAC ADDRESS shown at all.
OS UBUNTU 18.04.4 LTS.

**Comment by rt400** [comment]
need to install arp ..
sudo apt install net-tools

**Comment by Giochia** [comment]
Thank you rt400, it now works !
