### ISSUE TITLE
An existing online network computer isn't found

### ISSUE THREAD

**Issue by lessharm** [angryip/ipscan#213]
Linux Mint 19.2 Cinnamon, Angry IP Scanner 3.6.2

Hello,

the mentioned computer can be pinged successfully via the terminal, but Angry IP doesn't show it after scanning. With wifi analyzer on my mobile phone it is found, too. All other network devices are found correctly. What can be the reason for this? The only thing I know is, that the computer ( a laptop) was recently updated from Win7 to Win10.

Thanks for any help and vest wishes

lessharm

**Comment by angryziber** [comment]
That would be interesting to debug... As Linux doesn't allow Raw sockets
for non-root users (needed to send ICMP ping packets), ipscan uses a
combination of TCP/UDP probes to see if the host is up. If your Windows
machine has a very strict firewall that just ignores any packets, then
pinging this way will not work. Do you know if the machine would respond on
any TCP or UDP port (even saying that it's closed)?

**Comment by lessharm** [comment]
Hello angryziber,

thank you for your answer. I have an Dual Boot with Windows and have tried it there with Angry IP and the mentioned computer is recognized (WINDOW ICMP.DLL). I'm sorry, but I don't know exactly, how I can try the things you've posted:

> Do you know if the machine would respond on
> any TCP or UDP port (even saying that it's closed)?

Can you please explain it, so I can try it out?

What I can tell, is, that I can get remote access to that computer via Remmina and VNC within the network, but I don't know, if this is relevant for this issue.

In any case many thanks and best greetings

lessharm

**Comment by lessharm** [comment]
I've tested a little bit with the settings in Angry IP Scanner. When I enable "TCP port probe", I got all results exept the mentioned one. With "UDP packet" only 2/3 of the results with TCP. The problematic computer I can see only with enabling "dead hosts", with the informations I got, when it was still alive. But I don't know what to do to test any TCP ond/or UDP ports. I would be very grateful for a little help in this regard.

**Comment by lessharm** [comment]
After an interesting hint on the Angry IP Scanner website I have tried running the app with administrator rights and then I could choose the ICMP method and the problematic computer is back again as alive. Surprisingly the TCP/UDP ports are aslo shown, if stated in the settings. So it seems more of a rights issue (user, administrator), doesn't it? Why can I use ICMP as administrator but not as (normal) user?

**Comment by angryziber** [comment]
RAW sockets are not allowed for non-root users on some systems for security reasons.
The built-in ping program actually has setuid root bit set, so that it always runs as root.

By the way, Angry IP Scanner has an option to `Scan dead hosts`. This will force all hosts to be scanned even if they cannot be "pinged".
