### ISSUE TITLE
How do you edit the "Comments" column?

### ISSUE THREAD

**Issue by sb06794** [angryip/ipscan#215]
I added a "Comments" column to the IP scan results so that I can manually enter a "Friendly Name" for each IP address.  However, I can't find a way to edit any entries in the "Comments" column.  How do I do it?
![Results](https://user-images.githubusercontent.com/20874766/68349501-5ef99f00-00cb-11ea-9c1c-a78723dd32d3.jpg)

**Comment by angryziber** [comment]
You double click the IP and it's there.

**Comment by sb06794** [comment]
Hi Anton,

Thanks for replying.  However, I still can’t get it to allow me to add my own comments.  For example, when I “double click the IP” for the router I get what I’ve pasted below:

 

IP:                   192.168.1.1

MAC Address:  98:FC:11:7D:DB:8A

Ping:                 0 ms

Hostname:        BERG-HOME

Comments:       [n/a]

 

The problem is that none of what it shows me when I double click is editable, including the “Comments” section.  How do I edit it once I double click the IP address?

Stu

**Comment by angryziber** [comment]
There is a separate comments input field below the main text area.

**Comment by sb06794** [comment]
Anton,

Thank you so much.  I don’t know why I hadn’t noticed the comment input field before, but it works perfectly.

Stu
