### ISSUE TITLE
Build from source fails Task :linux64.min FAILED

### ISSUE THREAD

**Issue by ErikLentz** [angryip/ipscan#223]
I'm trying to build from source on Fedora 31 x64. I have OpenJDK installed.

Debug log attached.

The reason I'm trying to build from source is to build a Copr repository for easy updating.

[output.log](https://github.com/angryip/ipscan/files/4065518/output.log)

**Comment by angryziber** [comment]
Can you please make it easier for me and paste here the last lines of the
build (without debug mode), where failure step/reason should be visible?

**Comment by ErikLentz** [comment]
I'm probably doing something wrong...

`./gradlew current > output3.log
Note: /mnt/5EACD860ACD8346D/HomeUpload/Github/ipscan/src/net/azib/ipscan/exporters/AbstractExporter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/5EACD860ACD8346D/HomeUpload/Github/ipscan/build.gradle' line: 171

* What went wrong:
Execution failed for task ':linux64.min'.
> exec returned: 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
`

**Comment by ErikLentz** [comment]
Here's the result when I run as root:

> 
> ./gradlew current
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Configure project :
> Using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre/lib/rt.jar for proguard minimization
> Using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre/lib/rt.jar for proguard minimization
> Using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre/lib/rt.jar for proguard minimization
> Using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre/lib/rt.jar for proguard minimization
> Using /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre/lib/rt.jar for proguard minimization
> 
> > Task :compileJava
> Note: /home/smegs/Github/ipscan/src/net/azib/ipscan/exporters/AbstractExporter.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> > Task :linux64.min FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/smegs/Github/ipscan/build.gradle' line: 189
> 
> * What went wrong:
> Execution failed for task ':linux64.min'.
> > Warning: Could not find file /home/smegs/Github/ipscan/build/libs/rpm/RPMS/x86_64/ipscan-3.6.2-1.x86_64.rpm to copy.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 31s
> 5 actionable tasks: 5 executed
>

**Comment by ErikLentz** [comment]
Nevermind, I got it to build. I don't know what I was doing differently before.

**Comment by angryziber** [comment]
Great!
Maybe you can share it for others having the same problem?

**Comment by albfan** [comment]
any task finished in .min is related with proguard.

Reviewing the errors, a fix like:

```
diff --git a/build.gradle b/build.gradle
index f63a51dd..cb03bfbe 100644
--- a/build.gradle
+++ b/build.gradle
@@ -150,8 +150,10 @@ def minimizeTask(String platform, Closure doMore) {
         (project.ext.javaModules + "java.desktop").each {
             libraryjars System.getProperty('java.home') + "/jmods/${it}.jmod"
         }
+        dontwarn
         dontobfuscate
         dontoptimize
+        dontpreverify
         dontnote '**'
         configuration 'ext/swt.pro'
         configuration 'ext/jna.pro'
```

should make it, let me know if a PR for that would be accepted and I can create it

https://www.guardsquare.com/manual/troubleshooting/troubleshooting#superclass
