### ISSUE TITLE
IPSCAN-WIN64-3.6.2.EXE NOT EXECUTING

### ISSUE THREAD

**Issue by laylantrin** [angryip/ipscan#224]
Getting error, "org.eclipse.swt.SWTError: item not removed".

OS: Windows 10 64-bit

**Comment by angryziber** [comment]
@laylantrin what exactly are you doing before you get this error?
I need to reproduce it before I can fix. Thanks

**Comment by angryziber** [comment]
Maybe upgraded SWT will help
