### ISSUE TITLE
Add option to include IPs and/or ranges

### ISSUE THREAD

**Issue by KSGTHB** [angryip/ipscan#225]
This is very fast tool, but i cant find how works txt file for IP ranges. Generally txt solution  is not good, very old. Need more usable solution, like ip ranges in Lizard  Network Scanner.

**Comment by angryziber** [comment]
Are you talking about import or export?

For import, any text file can be loaded and anything that looks like IP address or a hostname will be scanned. Port numbers can also be provided after a colon.

No range support currently

**Comment by angryziber** [comment]
Same as #234
