### ISSUE TITLE
Ping delay

### ISSUE THREAD

**Issue by BINARIO1974** [angryip/ipscan#226]
Goog morning, I have install the Angry IP, on the macbook pro, on MAC and WIN7 partition.

I have a problem, because the mac version indicate PING moore high if compared with windows.

- The version is the lastest for all two programs, and the configuration are identical.
- Macbook pro is used over WIFI for testing.
- The ping test is start first only with MAC, ad then only with PC.

**Comment by BINARIO1974** [comment]
An other detail:
- The windows 7-64, is a Parallels Image running at the same time on MAC 10.14.6. 
- All two IP, are set static, with the same GW and DNS.

**Comment by angryziber** [comment]
Mac and Win use different pinging protocols by default.

On Windows, there is system ICMP.dll that is used to send ICMP echo packets.

On Mac/Linux sending of ICMP is impossible for non-root users, so UDP/TCP workaround is used that requires more packets to be sent and thus longer times.

**Comment by angryziber** [comment]
How high are the numbers on Mac?
Is it some % higher?
