### ISSUE TITLE
Bug when i was installer in linux ubuntu

### ISSUE THREAD

**Issue by araujosistemas** [angryip/ipscan#227]
See the image with SO version.

![Captura de tela de 2020-02-06 23-09-25](https://user-images.githubusercontent.com/26754670/73994924-e9090c00-4935-11ea-8d1e-316017132438.png)

**Comment by angryziber** [comment]
Do any solutions from here work?
https://unix.stackexchange.com/questions/94497/org-eclipse-swt-swterror-no-more-handles-gtk-init-check-failed-while-runnin

Can you run any other GTK GUI apps like that?

**Comment by angryziber** [comment]
OK, I can reproduce this if I login as root, which doesn't own the X Session.
Please run ipscan as normal user or if with sudo from your normal user's session.
