### ISSUE TITLE
2.2.1 project file is corrupt

### ISSUE THREAD

**Issue by ibjohn** [angryip/ipscan#228]
I'm not a programmer by any means, but I can wack a little code.... Trying to import 2.2.1 project but both VS 2005 and 2019 says  "Cannot load the project due to a corrupt project file"

Is the problem that it is built with an older version and I need VS 6 or is there a work around?

**Comment by angryziber** [comment]
The version 2.x is unmaintained for many years already.
Maybe there was a problem moving the file from Subversion to git (e.g. wrong line endings), or maybe a VS 6 had a different project file format.
Anyway, if you get it working, a PR is welcome to the 2.x branch.
