### ISSUE TITLE
Version 3.7.0 not work in Ubuntu 19.10

### ISSUE THREAD

**Issue by fakhamatia** [angryip/ipscan#230]
I update today and not work and show message `g_signal_handler` 

![Screenshot from 2020-03-15 15-31-24](https://user-images.githubusercontent.com/20030910/76700988-2c436100-66d2-11ea-99ad-83a89360b241.png)

**Comment by angryziber** [comment]
My bad, in the mean time please use the "universal" deb:
DEB Package for Ubuntu/Debian/Mint, any architecture (e.g. 32-bit or ARM)

It works for 64-bit as well

**Comment by angryziber** [comment]
Fixed and updated all Linux 64 binaries, thanks for reporting!
