### ISSUE TITLE
HTTP Sender not working correctly

### ISSUE THREAD

**Issue by shalabio** [angryip/ipscan#236]
The HTTP sender fetcher fails to translate the \r\n at the end of GET request to actual /0d /0a when sending the request. Instead, when inspecting with web sniffer, it sends the actual text as is.

Heres the capture:

00000000  47 45 54 20 2F 73 79 73  74 65 6D 2F 64 65 76 69   GET /sys tem/devi 
00000010  63 65 49 6E 66 6F 3F 61  75 74 68 3D 59 57 52 74   ceInfo?a uth=YWRt 
00000020  61 57 34 36 4D 54 45 4B  20 48 54 54 50 2F 31 2E   aW46MTEK  HTTP/1. 
00000030  31 5C 72 5C 6E 5C 72 5C  6E                                     1\r\n\r\ n  

And so nothing gets sent until the double LFCR is encountered as for the GET requirements.

**Expected behavior**
Normally it should translate the return carriage to 0d0a0d0a hex values. The server then responds with whatever is requested.

* Versions (please complete the following information):**
 - Windows 10
 - Java version, 32
 - Version of Angry IP Scanner 3.7

**Comment by angryziber** [comment]
It seems that HTTPSenderFetcher was never implemented fully, thanks for pointing this out!
