### ISSUE TITLE
No longer finding live hosts

### ISSUE THREAD

**Issue by coltrane58** [angryip/ipscan#238]
I am running v 3.7 of Angry IP on MacOS 10.15.4. I downloaded Angry IP Scanner a few weeks ago and it successfully identified hosts. Now it does not detect any hosts. I am using IP Range 192.168.1.0 - 192.168.1.255. I have tried UDP packets and TCP Port Probe, but with no hosts found. This is with Display Alive hosts only. If I select All Scanned Hosts it lists all 256 as alive only showing Mac Addresses for those IPs that are alive. I originally installed AIPS on MACOS 10.3 and it ran fine. It then stopped finding hosts. I have since upgraded to MacOS 10.15.4 and still the problem. I wish I could give steps but basically I just hit start and I get nothing. I have upped the ping timeout to 5000. Delay between threads 20, maximum threads 100. On the scan complete popup it says total time: 58.34, Ave time per host: 0.23, hosts scanned 256, hosts alive: 0. I have tried Alive hosts only and hosts with open ports. 
I cannot seem to find the commandline version. Is there one on the MacOS distribution?

**Comment by angryziber** [comment]
You can get to the command-line by executing `Angry IP Scanner.app/Contents/MacOS/ipscan -h` from the Terminal.

**Comment by angryziber** [comment]
I have just tried running the scanner on the Mac - it finds hosts no problem.
What is the type of devices that it cannot detect in your case? If they are computers, then which OS are they running? Is there a firewall?

**Comment by angryziber** [comment]
Please download this pre-release build and try the new Java Built-in pinger (select it in the Preferences): https://github.com/angryip/ipscan/actions/runs/102881191

Does it work for you?

**Comment by coltrane58** [comment]
Sorry for the less than timely response. That’s the strange thing, when I first downloaded and ran it it ran perfectly and I loved it. Maybe 5 or 10 days later it didn’t return anything. I started to play around with the settings such as increasing the ping response time but it didn’t help. If I set it to display all scanned hosts it returns all ip, even ones without a host, to blue and at least shows the MAC addresses and vendors but no ports. I’ve included images for the default scan and one with Display all. I just downloaded the beta and will report back.

**Comment by coltrane58** [comment]
Well the pre-release didn’t work either. One thing to mention, I’ve been working with perl network utilities lately. I don’t see how this could affect anything since I have rebooted the system since I’ve had the problem. Actually, when I first downloaded and ran AIS I was running MACOS High Sierra. It stopped working under that OS. I have since upgraded to MACOS Catalina and still have the problem. I will agree with you that this has something to do with my network. 

This is a home network. There is a wireless cable modem. Some hosts are connecting via wireless. I also have a wireless bridge in my office which provides wired connections for hosts that do not have wireless capabilities. Host-wise I have 1 PC, 2 Macs, 1 wireless printer, 1 wired printer, 2 Nest thermostats, a Roku box, and a Windows laptop. I’m attaching a screen shot of another app, Network Radar, for reference. This app is my go-to network app. I am a retired software engineer (programmer). While shelter-in-place I decided to spend my time working on perl network utilities. Why? Why not 😊 

 

Cheers

 

John

**Comment by JonnyTech** [comment]
@coltrane58 imaged attached via email replies do not show in github, please attach them via the github issues page

**Comment by tnaami** [comment]
I am having a problem finding hosts with various versions of the 32 bit Angry IP on Server 2012 R2.  The 64 bit does not work for me.  I've tried 3.5,2   3.62  3.7.0  and 3.7.1.  Same exact 3.7.1 EXE on a Windows 10 Enterprise works just fine.

I can verify that hosts are there as I see them in the ARP table from the switch.  From the Serve 2012R2 NMAP "ping" scan finds them (nmap -sn 192.168.53.1-254) .  I am scanning a VLAN that has two different types of devices; network switches and wireless APs.  The network switches show up but the APs do not in Angry IP.  All of them show up in NMAP or command line PING.

I don't know if this is may help or not.

**Comment by angryziber** [comment]
@tnaami which Pinging Method do have selected? Try changing it to e.g. "Java Built-in".
Do you get any errors in the console if you run the app with `java -jar *.exe`?
