### ISSUE TITLE
3.7.1 lost the "Openers" function in Mac

### ISSUE THREAD

**Issue by trecowan** [angryip/ipscan#243]
**Describe the bug**
keyboard shortcuts for IP openers is missing in 3.7.1; is available in 3.7.0.

**To Reproduce**
1. Scan IP range, select IP with appropriately open port (example here: port 80)
2. Go to Commands > Open
3. Note there is no submenu option
4. Choosing the "Open" command does not do anything.
5. Using previously configured keyboard shortcuts (Command 1 for browser on Mac) does not perform any action.

**Expected behavior**
Hope to open website related to selected IP address.

**Screenshots**

**Versions (please complete the following information):**
 - Mac OS 10.15.4
 - Java version, 64 bit, Version 8 Update 251 build 1.8.0_251-b08
 - 3.7.1

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

**Comment by angryziber** [comment]
Does Right click, Open work for you?

**Comment by trecowan** [comment]
Hi Anton,

Yes, when I right-click, I do get the options (honestly hadn’t realized the feature was there).  





Just missing from the Menu option:

**Comment by angryziber** [comment]
The fixed build is available here:
https://github.com/angryip/ipscan/actions/runs/122912292

Will be released as 3.7.2

**Comment by trecowan** [comment]
Thank you!
