### ISSUE TITLE
Fix thread-safety in Config

### ISSUE THREAD

**Issue by vlsi** [angryip/ipscan#244]
`Config` pretends to be a singleton, however, it's implementation is not thread-safe.

https://github.com/angryip/ipscan/blob/0128d3cd0281d1d79d92a33a270809f8c5eeb449/src/net/azib/ipscan/config/Config.java#L46-L52

https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom would be both shorter and safer than the current code. WDYT?

**Comment by angryziber** [comment]
This class predates the DI in the code. However, it is always accessed for the first time when everything is still running in 1 thread, so I guess there are no practical issues here

**Comment by vlsi** [comment]
>I guess there are no practical issues here

That is why I added "would be both **shorter**".

Even though you might know this code is always accessed from a single thread only, it would still help others to read and reason on the way the code operates.

Below is slightly less verbose than the code in `master` (`if` is not required):

```java
class Config {
 	// https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom
 	private static class ConfigHolder {
 	 	static final Config INSTANCE = new Config();
 	}
 	public static Config getConfig() { 
 		return INSTANCE;
 	}
```

If lazy initialization is not required, then `private static final Config INSTANCE = new Config();` in `Config` would do.
