### ISSUE TITLE
KDE programm appearence is terrible

### ISSUE THREAD

**Issue by malec985** [angryip/ipscan#247]
Please, fix programm appearence in KDE. fonts merge with the background. screen is attached
![Screenshot_20200527_183430](https://user-images.githubusercontent.com/40349745/83042048-db44d700-a049-11ea-8fc9-f97292795475.png)

**Comment by angryziber** [comment]
Are you using some dark theme in KDE? Which distribution?
Angry IP Scanner uses SWT on top of GTK on Linux, do other GTK apps look fine?

**Comment by malec985** [comment]
> Are you using some dark theme in KDE? Which distribution?
> Angry IP Scanner uses SWT on top of GTK on Linux, do other GTK apps look fine?

Im using kubuntu 19.10. Dark theme. other gtk apps looks ok.

**Comment by adbarbosa** [comment]
> Please, fix programm appearence in KDE. fonts merge with the background. screen is attached
> ![Screenshot_20200527_183430](https://user-images.githubusercontent.com/40349745/83042048-db44d700-a049-11ea-8fc9-f97292795475.png)

at least you can read  the text in my pop!_os with KDE it looks like this:
![Screenshot_20200611_205448](https://user-images.githubusercontent.com/7488676/84434091-4a642300-ac27-11ea-90a8-8513c0397baa.png)

**Comment by Dynan7** [comment]
same problem
kubuntu 20.04
![2020-07-06_11-40](https://user-images.githubusercontent.com/5037509/86563286-8ae06380-bf7d-11ea-8db3-c9f71b30137d.png)

**Comment by angryziber** [comment]
Upgrade of SWT seemed to fix, will be released as 3.7.3
