### ISSUE TITLE
Scan Results now are 100% red. Nothing being found

### ISSUE THREAD

**Issue by JWPepperSheriff** [angryip/ipscan#251]
Did I break the scanner or did it break itself? Changed IP to 192.168.200.x . Scanning range .1 to .255. All red. 
I am able to ping individual IP address and get results.
Is there a log file I can share?
[ip_scanner_red_results.txt](https://github.com/angryip/ipscan/files/4934304/ip_scanner_red_results.txt)

**Comment by angryziber** [comment]
What is your OS?
Please try other pinging methods in Preferences. Does anything work?
