### ISSUE TITLE
Java version 1.8 but 1.7 is required

### ISSUE THREAD

**Issue by pj-camp** [angryip/ipscan#254]
**Describe the bug**

This message appears every time I try to start the program. "Error registry key 'Software\JavaSoft\Java Runtime\Environment\CurrentVersion' has value '1.8' but 1.7' is required.

**To Reproduce**
Install on Windows 10
Try to start the program

**Expected behavior**
Pretty much anything but that, especially since Java 1.7 was eol'd 4 years ago

**Versions (please complete the following information):**
 - OS type and version 
Windows 10 version 10.0.18362 Build 18362

 - Java version, 32 or 64 bit, how was installed (`java -version`)
64 just downloaded from Oracle. Also installed OpenJDK 11.0.8 to try to fix the problem as it says on the download page

 - Version of Angry IP Scanner
3.7.2

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

No logs. Same error message.

I found an issue #111 regarding this. It ends resolving a problem with Java 9, but says nothing about resolving the problem with the 1.7 runtime

**Comment by angryziber** [comment]
Hello, the newer Windows launcher never outputs anything like this. Moreover, Angry IP Scanner is compiled to run on Java 1.8+, so I honestly don't understand where could this be coming from.

* Do you get the error during installation or during running?
* Are you sure you are not trying to start some older version of Angry IP Scanner?
* Can you run any other Java program?

Please provide a screenshot, maybe this will give a clue.
