### ISSUE TITLE
ip angry scanner /angry ip scanner 2.21

### ISSUE THREAD

**Issue by neo598** [angryip/ipscan#255]
when you type 169.168.0.2 in the box that is  after the message "ip range:" .
the first ip address, 169.168.0.2 will show up in the 2nd box i.e  the box after the message "to" 

for no reason.(1st bug)
you need to get rid of that ip in the 2nd box and  put 169.168.2.1 in its place.

click start, you will see it saying 36 threads then 100 then 93 and then 100 and lower then 93 and 100. (this is the 2nd bug)
                                                                                                                                                               
1. Go to 'the icon .' that says commands
2. Click on open
 Click on edit openers
click the icon add
3. put cmd in the opener name box
4. there will be an empty box(square) you should tick, tick the box(square) there will be a message on the right side of the box saying run in terminal.
5. put  C:\Users\user 123\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\System Tools in the working directory box click ok.
![Screenshot (69)](https://user-images.githubusercontent.com/68822778/88489370-cb833980-cf8b-11ea-90b1-af289eda301b.png)

6. Go to 'the icon .' that says commands
7. Click on open
 8. click cmd
type start_169.168.0.1_end_169.168.2.1 angry ipscanner 2.2.1.exe
type <start_169.168.0.1> <_end_169.168.2.1> angry ipscanner 2.2.1.exe
the angry ip scanner  command  line parameters showed
<start_ip> <end_ip> {filename} and so on
![Screenshot (75)](https://user-images.githubusercontent.com/68822778/88489572-dee2d480-cf8c-11ea-9cab-c50fd61875c1.png)

i did <start_169.168.0.1> <_end_169.168.2.1> angry ipscanner 2.2.1.exe
it said < was unexpected at this time
![Screenshot (73)](https://user-images.githubusercontent.com/68822778/88489539-ad6a0900-cf8c-11ea-8210-f2fa335feb19.png)

i did start_169.168.0.1 end_169.168.2.1 angry ipscanner 2.2.1.exe
it said 'start_169.168.0.1' is not recognized as an internal or external command,
operable program or batch file.
maybe start_169.168.0.1 end_169.168.2.1 angry ipscanner 2.2.1.exe is the correct way to apply the parameter but the command is not working or <start_169.168.0.1> <_end_169.168.2.1> angry ipscanner 2.2.1.exe is the right way to apply the parameter but the command is not working.

<start_169.168.0.1> <_end_169.168.2.1> angry ipscanner 2.2.1.exe is more likely the correct way to apply  the parameter then start_169.168.0.1 end_169.168.2.1 angry ipscanner 2.2.1.exe, based on how its more functional then start_169.168.0.1 end_169.168.2.1 angry ipscanner 2.2.1.exe

it said < was unexpected at this time (possible/probable bug)
this is confusing, how am i supposed to interpret the command line parameter? what do i put in cmd to make it work?

it should say exactly how to use the parameter in a very clear way.

i expected the <start_ip> <end_ip filename to work. i saved the filename of the ip result.
![Screenshot (71)](https://user-images.githubusercontent.com/68822778/88489411-f66d8d80-cf8b-11ea-9c7a-222f3110afad.png)

this occured on my windows 10 64bit laptop.

i have a java 64bit, but thats not relevent. i am only mentioning it, because this page suggested to mention it and it doesn't make sense, that the page suggested me to mention it.
  its not important. its stupid, ridicules.

it was installed through the internet. 
this Version of the Angry IP Scanner is version 3.7.2(the latest version) 

i run Angry IP Scanner from command-line and there was no relevant tags.
this page told me to run, Angry IP Scanner from command-line and see if there were any 
relevant tags. 
i removed the dumb message, so that is why you don't see it.

**Comment by JonnyTech** [comment]
Rename the application to something without spaces ie ipscan.exe then in the command prompt try:

`ipscan 192.168.0.1 192.168.0.255`

Assuming that is the IP range that your subnet is within.

**Comment by neo598** [comment]
hi
i did everything you suggested, but it didn't work.  that subnet is in the ip range.
it would be easier to understand the bottom part of your message, if you said assuming that subnet is within that ip range. because when you write it as Assuming that is the IP range that your subnet is within. it doesn't make sense. you have to read about 4 times to figure out what you really meant.

i will change, the ip range in the command to make the subnet within the range.

**Comment by JonnyTech** [comment]
Please research and learn about how subnetting and network visibilty work.

In very simple and brief terms:

If IP address is `192.168.0.123` and subnet is ` 255.255.255.0` then only `192.168.0.0 to 192.168.0.255` are visible and scannable.

If IP address is `192.168.1.55` and subnet is ` 255.255.255.0` then only `192.168.1.0 to 192.168.1.255` are visible and scannable.

...etc...

Note the third octect (192.168.**XXX**.YYY) and subnet (255.255.255.0) values.

(Experts, please don't shoot me down for the extermely basic example)

As you use windoze then you can view and change your ip address graphically in control panel or system settings to fall within the range that you require.

Also note that two devices cannot have the same ip address on the network, so make sure that each has a different fourth octect (YYY from above example).
