### ISSUE TITLE
Feature Request: Blacklist interfaces and/or set a default interface

### ISSUE THREAD

**Issue by ipha** [angryip/ipscan#257]
**Is your feature request related to a problem? Please describe.**
The auto-filled IP range always selects the "wrong" interface. 
Between HyperV and VPNs, I frequently have 5+ interfaces active, most of which I never want to scan. 
https://i.imgur.com/SggIKsA.png

**Describe the solution you'd like**
An option to blacklist certain interfaces so that VPN/VM interfaces don't show up in the interface list.

**Describe alternatives you've considered**
Maybe default to a physical interface instead of VPN/VM interfaces? Not sure if this is easy to detect though.

**Comment by angryziber** [comment]
Detection on Windows has improved (preferring interfaces closer to the beginning of the list)
