### ISSUE TITLE
Favorites doesn't work 

### ISSUE THREAD

**Issue by PlayeroS** [angryip/ipscan#258]
Hello
After store as favorite an scanned ip range  when I start again the app and execute the favorite doesn't appear the ip range that I have stored in my favorite.

Allways appears 192.168.xxxx in IP column but scans the stored range.

Version used 3.7.2

**Comment by angryziber** [comment]
Cannot reproduce the problem with 3.7.2/Linux.
Which OS are you using? Can you please describe more exact steps?

**Comment by fall-with-style** [comment]
This has never worked for me as well. I've used Windows 7 and 10
