### ISSUE TITLE
Comments doesn't work

### ISSUE THREAD

**Issue by PlayeroS** [angryip/ipscan#259]
Hello

After scanning an IP range , I write some comments and save as favorite.
When I start again the app and execute the favorite doesn't appear the Comments in te comment column, but with a doble click on the selected ip appars the comment.

Version used 3.7.2

**Comment by angryziber** [comment]
Comments are attached either to the MAC address (if available in the results) or to the IP.
If you attach comments to a MAC and then remove the fetcher, the comments will not show up during the next scan.

Another possibility is something is deleting corresponding registry key or config files between the runs. What might it be?
