### ISSUE TITLE
pings fail

### ISSUE THREAD

**Issue by coltrane58** [angryip/ipscan#260]
When I run Angry IP all the pings fail except for the router. When I run Network Radar the pings are successful. I can also successfully ping from the command line. 

I have tried to run AI from the commandline. I got the same results. I did notice that the MAC addresses and manufacturers where correctly retrieved.

This is on a Mac Mini Late 2014. OSX 10.15.6. I am running Angry IP v 3.7.2. 
The host is connected to a Cisco wireless bridge which has a wi-fi connection to a cable router. 

![Screen Shot 2020-09-06 at 7 08 15 AM](https://user-images.githubusercontent.com/6958853/92324566-f217a400-f010-11ea-9a75-ca1cc55a57c3.png)
![Screen Shot 2020-09-06 at 7 07 57 AM](https://user-images.githubusercontent.com/6958853/92324567-f5ab2b00-f010-11ea-866f-896fa91e039e.png)
[pingoutput.txt](https://github.com/angryip/ipscan/files/5179614/pingoutput.txt)

**Comment by angryziber** [comment]
Please try other Pinging methods in the Preferences and report the results.
By default, a combination of UDP and TCP probes is used and probably your router sends some unexpected replies, resulting in IPs to be incorrectly shown as alive. It would be great if you could capture/sniff the IP packets and paste here, which e..g UDP replies are being sent on your network.

Note: ICMP pinging on a Mac is currently only possible by running as root (with sudo) and selecting Java Built-In pinging method.
