### ISSUE TITLE
Wrong MAC Address look up

### ISSUE THREAD

**Issue by holdgaard1977** [angryip/ipscan#265]
**Describe the bug**
Wrong MAC addresses are shown. 

**To Reproduce**
Installation and test-Setup: 
Angry IP Scanner is installed on Windows 10 x64 on a VMware Workstation.
Inside this Windows 10 machine a Cisco Any Connect is established to the remote site with 10.20.209.0/24
It's possibly to ping the devices and also for e.g. 10.20.209.11 to connect to this host using my browser (it's a HIKVision NVR). 

When form Windows command prompt doing a arp -a, the mac addresses are the same

From attached file the problem can be seen. 
**Expected behavior**
Should show correct mac addresses.

**Screenshots**
![2020-10-16_10-39-43](https://user-images.githubusercontent.com/65340242/96236718-a99ebf00-0f9c-11eb-9791-d9e5580928f3.png)

**Versions (please complete the following information):**
 - Windows 10, version 10.0.18363.1082
 - Java version: 
C:\WINDOWS\system32>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode, sharing)
 - Version of Angry IP Scanner

**Logs:**
![2020-10-16_10-39-43](https://user-images.githubusercontent.com/65340242/96236917-eff41e00-0f9c-11eb-948d-13b6c78f543f.png)

- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

**Comment by angryziber** [comment]
These MAC addresses are returned by your system.
On Windows, Angry IP Scanner uses the standard SendARP() function to get the MAC.
It seems that something on your machine is spoofing the results of this function.

**Comment by MangoYou** [comment]
so do i ,when I scan the vmware host,it feedback the physical host mac instead of vmareware mac
