### ISSUE TITLE
IP scanner does not work with JDK 15.0.1

### ISSUE THREAD

**Issue by rfm1** [angryip/ipscan#266]
**Describe the bug**
According to the Angry IP scanner website:

        "Make sure you have at least Java 8 or OpenJDK installed - check your distribution."

I checked my java level from terminal as so
------------------------------
> root@localhost:/home/randy/Downloads# java -version
> java version "15.0.1" 2020-10-20
> Java(TM) SE Runtime Environment (build 15.0.1+9-18)
> Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
-------------------------------
I then tried to install IP scanner
-------------------------------
>root@localhost:/home/randy/Downloads# dpkg -i ipscan_3.7.2_amd64.deb
>Selecting previously unselected package ipscan.
>(Reading database ... 70564 files and directories currently installed.)
>Preparing to unpack ipscan_3.7.2_amd64.deb ...
>Unpacking ipscan (3.7.2) ...
>dpkg: dependency problems prevent configuration of ipscan:
 >ipscan depends on openjdk-14-jre | openjdk-13-jre | openjdk-12-jre | openjdk-11-jre | openjdk-10-jre | oracle-java10-installer | openjdk-9-jre | oracle-java9-installer | openjdk-8-jre | oracle-java8-installer; however:
>  Package openjdk-14-jre is not installed.
>  Package openjdk-13-jre is not installed.
>  Package openjdk-12-jre is not installed.
>  Package openjdk-11-jre is not installed.
>  Package openjdk-10-jre is not installed.
>  Package oracle-java10-installer is not installed.
>  Package openjdk-9-jre is not installed.
>  Package oracle-java9-installer is not installed.
>  Package openjdk-8-jre is not installed.
>  Package oracle-java8-installer is not installed.

>dpkg: error processing package ipscan (--install):
 >dependency problems - leaving unconfigured
>Processing triggers for desktop-file-utils (0.23-4) ...
>Processing triggers for mime-support (3.62) ...
>Errors were encountered while processing:
 >ipscan
-----------------------------------
This is a new Debian 10 Buster install.

Is this app still being maintained?

(I apologize for the formatting of this issue.  I don't understand why this editor randomy makes things large and bold.)

**Comment by angryziber** [comment]
Good point, Java releases are a bit too frequent nowadays :-)
