### ISSUE TITLE
Let ipscan remember position on desktop

### ISSUE THREAD

**Issue by tobwz** [angryip/ipscan#278]
Ipscan remembers only its window size at exit.

But after restart it appears at another position on desktop.

Can you let Ipscan remember the desktop position beyond exit+restart as well?

**Comment by angryziber** [comment]
You have skipped the issue template...
Which OS, window manager?

**Comment by tobwz** [comment]
64bit Windows 7

**Comment by Gaubiche** [comment]
Hello ! We're a group of students that would like to contribute to the Angry Ip Scanner project. Are there some people working on this issue ? Or can we adress it ?

Thanks in advance
