### ISSUE TITLE
MacOS launcher should let the user know if Java is not available

### ISSUE THREAD

**Issue by jackjansen** [angryip/ipscan#279]
I was going to write a bug report "doesn't work on MacOS 11", but it turns out the problem was that Java is no longer installed by default.

There is indeed a small notice on the download page that you should "install java 8", but I overlooked that.

It would be sort of nice if the app would pop up a dialog if Java is missing on your machine, few people will have it installed nowadays... And right now the app does absolutely nothing if you double-click it without Java installed.

**Comment by angryziber** [comment]
Do you know how to popup a GUI dialog on macOS from command-line?

**Comment by llamafilm** [comment]
@angryziber there are several ways but one easy option is Apple Script: `osascript -e 'display dialog "You must install Java first" with icon stop with title "Angry IP Scanner"'`

**Comment by angryziber** [comment]
It's interesting that if you type `java` in the terminal, macOS would open a dialog prompting to install Java. Doesn't it happen if you try to run ipscan for the first time?
