### ISSUE TITLE
192.168.43.245

### ISSUE THREAD

**Issue by wsb81** [angryip/ipscan#282]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS type and version
 - Java version, 32 or 64 bit, how was installed (`java -version`)
 - Version of Angry IP Scanner

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

**Comment by illfated** [comment]
Oh. I see. Suggestion for a new and updated issue template, I presume?

**Comment by angryziber** [comment]
Nothing to do here
