### ISSUE TITLE
installer leaves a broken application - missing files

### ISSUE THREAD

**Issue by Dloranger** [angryip/ipscan#283]
**Describe the bug**
Running the installer (windows), I am left with an error for 

![image](https://user-images.githubusercontent.com/10390925/112368683-92c16e80-8c98-11eb-91bb-f5960b65dfec.png)

**To Reproduce**
install the program and try to run the application, error is presented

**Expected behavior**
application installs all required files and launches cleanly without user intervention

**Screenshots**
See image above

**Versions (please complete the following information):**
 - OS type and version: Windows 10 x64
 Java Version:
 openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
 - Version of Angry IP Scanner: 3.7.6

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.
- no logs, just the windows pop-up about missing file

**Comment by angryziber** [comment]
Are you trying to run it from a strange directory/path?
Please try 3.8.2, the installer now includes a Java runtime
