### ISSUE TITLE
Support for Mac M1 arm64

### ISSUE THREAD

**Issue by danielporto** [angryip/ipscan#284]
Title sums it up.
Currently there is no release nor the code compiles for Mac M1
Would be nice to have an universal version that installs via brew on both Mac architectures.

thanks

**Comment by angryziber** [comment]
That needs to wait until SWT (the UI toolkit) for M1 is available

**Comment by nickp-ca** [comment]
Was also using SWT in another project and it looks like in the last two weeks they have addressed this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565690

**Comment by dragoshenron** [comment]
@angryziber indeed you are right.
However SWT for M1 is available. Do you know when we can expect a new release?
Thanks

**Comment by luckman212** [comment]
I am trying to launch Angry on macOS Monterey 12.0.1 on an M1 Mac Mini... it just bounces forever and requires a force-quit.

I tried to launch from Terminal so I could see what was going on, it seems to be complaining about SWT still. I have java JDK 17.0.1 (arm) installed

```shell
java -XstartOnFirstThread -jar ./ipscan-mac-3.7.6.jar
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	no swt-cocoa-4940r23 in java.library.path: /Users/luke/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/luke/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib: dlopen(/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib, 0x0001): tried: '/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libswt-cocoa-4940r23.jnilib' (no such file)
	Can't load library: /Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib: dlopen(/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib, 0x0001): tried: '/Users/luke/.swt/lib/macosx/aarch64/libswt-cocoa-4940r23.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libswt-cocoa-4940r23.jnilib' (no such file)

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:338)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
	at net.azib.ipscan.gui.GUI.<init>(GUI.java:29)
	at net.azib.ipscan.Main.main(Main.java:47)
```

**Comment by ju5t** [comment]
It doesn't even bounce here, it just doesn't do anything. The icon doesn't even appear. I tried the PR from @aplr but that didn't work for me due to some java errors (got the JRE and JDK).

**Comment by aplr** [comment]
@ju5t what exactly did not work for you? I also had to mess around with the jdk/jre settings in Idea, I'm definitely not a Java guy. However I did not commit these changes as I thought these were quite environment-specific and might interfere with the existing release configuration.

**Comment by ju5t** [comment]
@aplr I'm not a Java guy either. I just installed the JRE and JDK and tried to run the ./gradle commands. The error I got was:

```
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x76e64c94) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x76e64c94
```

**Comment by angryziber** [comment]
@ju5t Normally, you need Java 11 to build the app.
I have updated master branch to be able to build with Java 17 as well.

@aplr PR has been merged to master as well, thanks!

**Comment by angryziber** [comment]
3.8.0 released
