### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by IT-Ranger** [angryip/ipscan#288]
Hope I'm not being dense, but I can't export results in any file format. .txt .csv I'm running Windows 10 20H2

**To Reproduce**
Scan > Export Export All or Selection
Choose any file format, it fails to create the document. If I create a blank text file and try to export to it, that doesn't work. I tried running as administrator, no change. 

**Expected behavior**
I expect it to export a file containing the results of my scan in the selected file format. 

**Screenshots**

**Versions (please complete the following information):**
 - Windows 10 20H2
 -8-281 32  bit.  This might be the issue. We have an Enterprise deployment of Java that is preconfigured and uneditable. So if you think this is the issue, you can close this immediately unless you have a workaround.
 - version 3.76, but also had the issue on 3.74

**Logs:**
- Didn't see any logs but this question led me to discovering how to run ipscan from a command line, and I was able to export results successfully from a command line. So this is an FYI, and if you think it's not your issue, feel free to close.

**Comment by illfated** [comment]
When you try to export to a file in the GUI part of the program, which folders did you use or test?

Could it be that you are trying to save a file to the C:\Program Files\ folder, where you would need to start the program with local administrative privileges to save anything?

**Comment by IT-Ranger** [comment]
No, I was saving to C:\Temp



Joe Jett

Region 1 Technology Officer (Acting)

IT Specialist

New River Gorge National Park and Preserve

304-640-7617       cell

304-465-6546       office

Schedule an appointment with ***@***.***/bookings/>



________________________________
From: Trond B. Krokli ***@***.***>
Sent: Sunday, April 18, 2021 11:34 AM
To: angryip/ipscan ***@***.***>
Cc: Jett, Joseph ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [angryip/ipscan] Can't export (#288)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



When you try to export to a file in the GUI part of the program, which folders did you use or test?

Could it be that you are trying to save a file to the C:\Program Files\ folder, where you would need to start the program with local administrative privileges to save anything?

**Comment by illfated** [comment]
> No, I was saving to C:\Temp

Fair enough, that does not look like a user rights issue then. I don't know what else to suggest, so I hope one of the team members will be able to suggest something else to try.

**Comment by angryziber** [comment]
Please try 3.8.2 with bundled Java.
Closing as there are not other ideas
