### ISSUE TITLE
Windows installer is not silent if JVM is not found

### ISSUE THREAD

**Issue by chausner** [angryip/ipscan#292]
**Describe the bug**
Since https://github.com/angryip/ipscan/commit/273e6e1e2853b58fed469bc6ba9b6ebb1f1b1516, a message is displayed by the installer if no JVM is found. The message is shown even when the installer is invoked with /S for silent install. I suggest to not show any message in this case because it can make it hard to write automation scripts (that might install the JVM afterwards).

**To Reproduce**
1. Run `ipscan-3.7.6-setup.exe /S` on a machine with no JVM installed

**Comment by angryziber** [comment]
Fixed in master. The installer will not include the JRE and be totally silent
