### ISSUE TITLE
Java VM Launcher Could not find the main class

### ISSUE THREAD

**Issue by VrigaChabibi** [angryip/ipscan#293]
**Describe the bug**
Started from 3.6.2, it is always failed to run and give me the following message: Could not find the main class. Program will exit.

**To Reproduce**
1. Just double-click portable version of x64

**Expected behavior**
It was running well at 3.6.1

**Screenshots**
![image](https://user-images.githubusercontent.com/55678945/120108913-ca1d3180-c199-11eb-9eb8-c86b3ecb5536.png)

**Versions (please complete the following information):**
 - Windows 10 Pro 20H2 19042.985
 - Java 64 bit, java version "1.8.0_291", Java(TM) SE Runtime Environment (build 1.8.0_291-b10), Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
 - Version of Angry IP Scanner 3.6.2

**Comment by angryziber** [comment]
What is a "portable version"? Where are you getting it from?

**Comment by VrigaChabibi** [comment]
ah, I'm sorry, maybe it is called executable version
I get it from here https://github.com/angryip/ipscan/releases/download/3.6.2/ipscan-win64-3.6.2.exe

**Comment by illfated** [comment]
> What is a "portable version"? Where are you getting it from?

Good question, I was trying to think of whether it could be something I hadn't noticed in the app from https://patchmypc.com/ .

**Comment by angryziber** [comment]
Please make sure that your Java can be run from the terminal by typing `java` or `javaw` - select "Add to system path" when installing
