### ISSUE TITLE
Default ip range is wrong/useless

### ISSUE THREAD

**Issue by Dan-Essin** [angryip/ipscan#298]
**Describe the bug**
When the app opens the ip range is set to 192.168.56.0/24

My lan uses 192.168.1.0/24

The default is useless. Other scanning apps, such as lanscan, on mac don't seem to have trouble detecting the subnet range.

**To Reproduce**
1. Open the app
2. See the wrong range

**Expected behavior**
![aips](https://user-images.githubusercontent.com/1776053/131733897-da945e3d-98be-4e1b-88c0-3e55576b9d96.jpg)
**Screenshots**

-----
The problem is that it is detecting the ip address of the Virtual Box soft Host-only ethernet instead of detecting the hardware ethernet adapter.

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::743b:e513:d786:2339%14
   IPv4 Address. . . . . . . . . . . : 192.168.1.132
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::2e0:67ff:fe12:1171%14
                                       192.168.1.4

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::2d0a:f756:1857:7a80%8
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Scanning the range implied by the vbox ip would be futile because the range doesn't actually exist.

It should NOT choose an ip that has no associated default gateway, which would exclude all "adapters" created by VMware and VirtualBox.

**Versions (please complete the following information):**
OS type and version
Device name	A
Processor	AMD Ryzen 7 3800X 8-Core Processor                3.89 GHz
Installed RAM	64.0 GB
Device ID	B166D701-FF05-41FC-B651-FC937CCA7DC8
Product ID	00330-80000-00000-AA401
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

 - Java version, 32 or 64 bit, how was installed (`java -version`)
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

 - Version of Angry IP Scanner
 3.7.6

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.
No Logs written

**Comment by angryziber** [comment]
Please check newly released version 3.8.0.
Also, you can use the IP^ button to select the interface that you need if the default one cannot be detected correctly.
