### ISSUE TITLE
Linux Qt 5.5.1 (HP ThinPro 7.1 OEM Ubuntu 7.04 LTS x86_64) Misaligned UI button

### ISSUE THREAD

**Issue by mj162** [angryip/ipscan#299]
In version 3.7.6:

![3.7.6](http://cloud.tel.co.uk:8192/dropbox/ipscan-linux64-3.7.6_page1.png) the label on the "IP Range" drop-down in the top centre of the main screen disappears on occasion, and base of the the drop-down buttion is partly below the "IP Range:" from and "to" (missing colon) entry fields rather than horizontally aligned.  As a result the blue "Start" button is half pushed-off the header in comparison with version 3.7.2 that displays correctly.

![3.7.2](http://cloud.tel.co.uk:8192/dropbox/ipscan-linux64-3.7.2.png).

**Comment by angryziber** [comment]
Hmmm... cannot find any relevant layout changes in the code between 3.7.2 and 3.7.6. This is probably a result of SWT update.
What about 3.8.x?
