### ISSUE TITLE
v3.7.6 Build issue on Solaris 11

### ISSUE THREAD

**Issue by mj162** [angryip/ipscan#300]
**Build failed with an exception**
An exception occurred applying plugin request [id: 'com.palantir.git-version', version '0.12.2']; cannot find '.git' directory].

**To Reproduce**
1. Downloaded v3.7.6 source into /tmp and
2. Tar extracted all into /tmp
3. `cd /tmp/ipscan-3.7.6`
4. `./gradlew current`
4. See error as above

**Expected behavior**
A successful build (or clues how to run the `ipscan-any-3.7.6.jar` successfully on Solaris.

**Versions (please complete the following information):**
 - OS type and version: Solaris 11.3 SPARC
```
        SunOS Release 5.11 Version 11.3 64-bit SPARC  Host ID: 85015d80
                         (Oracle Solaris 11.3.34.0.4)
``` 
- Java version, 32 or 64 bit, how was installed (`java -version`)
 ```
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
```
(Java 11 also available/installed)
- Version of Angry IP Scanner: 3.7.6

**Logs:**
```
$ ./gradlew current
Downloading https://services.gradle.org/distributions/gradle-6.7-bin.zip
..................................................................................................
Unzipping /home/mj162/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7-bin.zip to /home/mj162/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv
Set executable permissions for: /home/mj162/.gradle/wrapper/dists/gradle-6.7-bin/efvqh8uyq79v2n7rcncuhu9sv/gradle-6.7/bin/gradle

Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/ipscan-3.7.6/build.gradle' line: 12

* What went wrong:
An exception occurred applying plugin request [id: 'com.palantir.git-version', version: '0.12.2']
> Failed to apply plugin 'com.palantir.git-version'.
> Cannot find '.git' directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
```
**Skill Level**
I am not a developer.

**Comment by angryziber** [comment]
The first error you get is because you haven't cloned the git repo, but just downloaded the archive, so a version number could not be determined. Maybe this should be fixed.

Secondly, Solaris was never supported by ipscan. The reason is the SWT library that is used for native GUI: https://www.eclipse.org/swt/

If you get an unofficial SWT build for Solaris/GTK, then ipscan may be able to run.

**Comment by mj162** [comment]
Running Angry IP Scanner on Solaris is no-longer an issue given that the jNetMap Network Monitoring app v0.5.5 [https://rakudave.ch/jnetmap/](https://rakudave.ch/jnetmap/) that does an equally good job of device discovery but also has a map diagrammer.  It appears to be pure java; the same app running on our HP ThinPro (Ubuntu-based) desktops and on our servers including Solaris SPARC...
