### ISSUE TITLE
Scanner on Windows 2019 returns zero results

### ISSUE THREAD

**Issue by JerkyChew899** [angryip/ipscan#302]
**Describe the bug**
Running the scanner on my LAN returns zero alive hosts. I've tried ports 22, 443, 80 all separately. The scan works fine on my Windows 10 laptop on the same LAN

**To Reproduce**
1. Launch app
2. Go to settings, set port
3. Scan LAN (full /24)

**Expected behavior**
I expect to see several alive hosts, as they appear in the Windows 10 version

**Screenshots**

**Versions (please complete the following information):**
 - Windows Server 2019 OS Build 17763.2114
 - openjdk version "16.0.2" 2021-07-20
    OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
    OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
 - Version of Angry IP Scanner - 3.7.6

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

**Comment by JonnyTech** [comment]
Please open the relevant ports on the windows server firewall - or disable it completely.

**Comment by JerkyChew899** [comment]
Windows firewall is already disabled, and I can connect to several hosts on the LAN over HTTP/S, SSH, SMB, etc.

**Comment by angryziber** [comment]
There's a report that it works with Liberica JDK, can you check?
https://bell-sw.com/pages/downloads/#/java-17-lts

**Comment by angryziber** [comment]
@JerkyChew899 what about version 3.8.2? It has the correct Liberica Java bundled if you use the installer.
