### ISSUE TITLE
Problem with dark Desktop Theme on Linux (Raspberry OS)

### ISSUE THREAD

**Issue by kosmosgit** [angryip/ipscan#304]
see the picture
![Angry_IP-Scanner](https://user-images.githubusercontent.com/60920023/133021671-4d594063-c6dd-49e6-b494-94df40794bf0.png)

in /home/pi/.java/.userPrefs/ipscan/prefs.xml there are not a color config

**Comment by angryziber** [comment]
Please check version 3.8.0 with updated SWT
