### ISSUE TITLE
windows - some devices not detected

### ISSUE THREAD

**Issue by Dan-Essin** [angryip/ipscan#306]
**Describe the bug**
I have aip installed on 2 win 10 boxes.
on one the scan find 60 devices.
On the other it only finds 30.

**To Reproduce**
On the problem machine it always the same thing. Several updates ago it worked as expected.

**Expected behavior**
see all devices
**Screenshots**

**Versions (please complete the following information):**
 - OS type and version - win 10 64-bit latest version
 
 - Java version, 32 or 64 bit, how was installed (`java -version`) java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)

 - Version of Angry IP Scanner 3.7.6

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written.
No logs written
![machine B](https://user-images.githubusercontent.com/1776053/133846393-9563bca1-1d33-44e7-8f57-3d8798f1f4f6.jpg)
![machine A](https://user-images.githubusercontent.com/1776053/133846395-53e1d794-6ca0-429a-bac9-2f799bfba4b3.jpg)
.

**Comment by angryziber** [comment]
Please try version 3.8.2, which will now try ARP ping automatically for local network addresses, this should detect local hosts that don't respond to normal pings.

Also, now you can choose ARP pinger in the Preferences.
