### ISSUE TITLE
Skipping IP's when scanning a range

### ISSUE THREAD

**Issue by dnyt84** [angryip/ipscan#309]
**Describe the bug**
I am Scanning an IP range, for example 192.168.56.250 - 192.168.57.20
In that range there are 12 valid IP addresses.
But the scanner only scan's 10 IP addresses skipping 192.168.56.255 and 192.168.57.0.
This is not correct behavior as the subnet is a /21 and 255 and 0 are valid IP addresses.

Similar to public space where .0 and .1 or .254 and .255 can be valid when either it is part of a larger subnet or a /31 subnet.
we use /31 on Point to Point links.

Same behavior when scanning for a /23, it skips the .0 and .255 address out of both subnets even though the IP Range specifies x.x.14.0 to x.x.15.255.

**To Reproduce**
Scan 192.168.56.250 - 192.168.57.20 and only 10 IP's are scanned.
Scan 192.168.56.0/23
**Expected behavior**
Should be 12 IP addresses
**Screenshots**

**Versions (please complete the following information):**
 - Windows 10
 - Java version, 
 java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

 - Version of Angry IP Scanner: 3.7.6

**Comment by dnyt84** [comment]
bump

**Comment by angryziber** [comment]
You are right, this needs to be addressed.
Probably skipping must be done based on the chosen netmask for scanning. Unfortunately, it cannot be done with non-rangenbased scans.

In the meantime, you can disable this skipping in Preferences.
