### ISSUE TITLE
Can you give some examples running ipscan with options

### ISSUE THREAD

**Issue by JujuLand** [angryip/ipscan#310]
Hi, I'm not able to run ipscan with parameters.

Can you give some examples ?

`ipscan -s -f:192.168.1.24 192.168.1.24 -o scan.txt`

`***WARNING: GTK+ version too old (micro mismatch)`
`***WARNING: SWT requires GTK 3.20.0`
`***WARNING: Detected: 3.18.9`

`Feeder unknown: 24`

Thanks
A+

**Comment by angryziber** [comment]
Try running `ipscan -h` and it will tell you that you need to use `-f:range`, e.g.

```
ipscan -s -f:range 192.168.0.1 192.168.0.255 -o scan.txt
```

Note that you may want to add `-q` as well to quit after exporting the results to the file.
