### ISSUE TITLE
Comments dissapear or appear next to wrong hosts

### ISSUE THREAD

**Issue by JLNapo** [angryip/ipscan#311]
Comments don't work.
They are placed where they want!

**Comment by Thronborg** [comment]
Comment is a very good way to naming the units. But after adding comments some of them dissapear and i have to add dem again.

**Comment by angryziber** [comment]
Comments are attached to either MAC address (if present in the scan), or to the IP address.
If your hosts change IP addresses, then comments will stay at the old addresses.

**Comment by Thronborg** [comment]
Ok, thanks!

Vänlig hälsning
Ole Thronborg
Adamsdal
61197 Stigtomta
Mobil: 070-2763395
Epost: ***@***.***

**Comment by JLNapo** [comment]
Hello,
Thank you for your work.
For the comments, it may be necessary to review another way of doing things in development... I say that, but it may be difficult.

**Comment by angryziber** [comment]
From 3.8.2, Angry IP Scanner will always do an ARP ping in addition to a normal ping (if scanning LAN).
This should make MAC address always available for local devices and will attach comments to MACs.

Do you have any examples in which networks it didn't work?
Were these public or private IP ranges?
Any steps to reproduce?

**Comment by angryziber** [comment]
Hopefully the situation will improve with 3.8.2.
If not, please open a new issue with steps to reproduce.

**Comment by JLNapo** [comment]
Hello,
Thank you for your efforts, I think to encourage you, as I have already done, with a small contribution.
For version 3.8.2, when do you plan to upload it?
Thank you very much.
