### ISSUE TITLE
How to show mac addresses?

### ISSUE THREAD

**Issue by peter099** [angryip/ipscan#314]
Mac addresses are shown as [n/a] after lan scan for connected devices on my home network. How to make Angry IP Scanner show mac addresses? I am using version 3.7.6 on mx linux.

**Comment by angryziber** [comment]
On Linux, you need to have the `arp` utility available and runnable by the same user.

Also note that only local IP addresses can resolve to Mac addresses.

**Comment by peter099** [comment]
I have arp installed. I am not sure what you mean by `runnable by the same user`. 

I found that if i start the program from the terminal with `sudo ipscan` it shows the mac addresses, but if i start it from the start menu it won't show the mac addresses.

**Comment by angryziber** [comment]
That probably means that your current user has no permissions to run `arp`, you can try running it from the terminal

**Comment by Lifecycled** [comment]
I can confirm that running from a command prompt on windows10 solved this for me as well.
C:\Program Files\Angry IP Scanner>ipscan
