### ISSUE TITLE
Can Open Angry IP Scanner.app v3.7.6 on macOS BigSur 11.6 (20G165)

### ISSUE THREAD

**Issue by olygoelements** [angryip/ipscan#318]
after giving permission to start the application, it displays an error message: 1

**Comment by angryziber** [comment]
Please run Angry IP Scanner.app from terminal and see if there are any errors printed

**Comment by angryziber** [comment]
@olygoelements maybe you have a M1 ARM processor? In this case a fix is coming in version 3.7.7

**Comment by idna001** [comment]
I have a similar error.
Just can't open the latest version on my M1 Mac with Monterey 12.1, it closes right after opening with no error message.
What could I try? I gave the permission for opening that app, and dragged it into the Application folder.

Thanks for help

**Comment by idna001** [comment]
I have a similar error.
Just can't open the latest version on my M1 Mac with Monterey 12.1, it closes right after opening with no error message.
What could I try? I gave the permission for opening that app, and dragged it into the Application folder.

Thanks for help

**Comment by angryziber** [comment]
@idna001 Architecture of installed Java & Angry IP Scanner must match, Rosetta must be turned off.

Make sure you have downloaded the lastest version 3.8.2.

If it still doesn't work, please try to run `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan` from the Terminal and paste the output here.

**Comment by idna001** [comment]
Ahh, thank you, @angryziber, I had the wrong Java Version installed…
Now it works just fine 😀
