### ISSUE TITLE
Desktop file should have Keywords header

### ISSUE THREAD

**Issue by RedBearAK** [angryip/ipscan#321]
I guess the desktop file for this project is created during the build process, so I can't find it and don't know how to make a PR for it. 

It would be a good idea if the desktop file included a standard "Keywords" header, to make it easier for application launchers like Ulauncher, Albert or the GNOME app search to find and present the application to the user. 

Something like this, for example: 

```
[Desktop Entry]
Encoding=UTF-8
Name=Angry IP Scanner
Comment=Fast and friendly network scanner
GenericName=Fast and friendly network scanner
```
`Keywords=angry;ip;scan;scanner`
```
Exec=sh /usr/bin/ipscan
Terminal=false
Type=Application
Icon=ipscan
Categories=Application;Network;Internet;
StartupWMClass=Angry IP Scanner
StartupNotify=true
```

There are probably other keywords that might make more sense or be more helpful. 

An example of what happens in some application launchers without extra terms in the "Keywords=" header is that if you try to search for a sub-string like "torrent" an application might not appear if the "Comment=" header or "Name=" header only has the string "Bittorrent". Depends on the specific application launcher.

**Comment by angryziber** [comment]
The desktop file is actually in the repo - you can see it in the commit above or by searching in the repo

**Comment by RedBearAK** [comment]
@angryziber 

Very smart to add "ipscan" as another keyword by itself, which I forgot to do in my example.  Those familiar with using the terminal command will appreciate that. Problem solved. Thanks! 

![image](https://user-images.githubusercontent.com/64876997/149685705-b071cdf1-109f-49ba-b076-426cb5a5e713.png)
