### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [angryip/ipscan#323]
Dear @angryziber,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/ipscan/discussion/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/ipscan/

To disable/delete tabs, go here: https://sourceforge.net/projects/ipscan/
To add a new tab, go here: https://sourceforge.net/projects/ipscan/
To change informations, go here: https://sourceforge.net/p/ipscan/admin/overview
To export, go here: https://sourceforge.net/p/ipscan/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/ipscan/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/ipscan/admin/overview
- A new tab, go here: https://sourceforge.net/projects/ipscan/

Thanks in advance.

**Comment by angryziber** [comment]
@Neustradamus thanks for a good point. I have added the "moved" badge and updated some links.
Let the old discussions stay for now.

**Comment by Neustradamus** [comment]
@angryziber: Thanks for your reply and your improvements :)

Why to keep discussions?
People can always create at the old place...

**Comment by Neustradamus** [comment]
@angryziber: Thanks for your reply and your improvements :)

Why to keep discussions?
People can always create at the old place...
