### ISSUE TITLE
Can't open after install 3.8.0 Win 11 and Java 8

### ISSUE THREAD

**Issue by epizarro2** [angryip/ipscan#324]
**Describe the bug**
After update ipscan to 3.8.0 setup, doesn't start

Java Virtual Machine Launcher
---------------------------
Error: A JNI error has occurred, please check your installation and try again

Rolling back to 3.7.6 and works

**To Reproduce**
1. Go to site, download, update
2. Click on ipscan shortcut
3. See error

**Versions (please complete the following information):**
 - OS type and version
Windows 11 Pro N 21H2 22000.434

 - Java version, 32 or 64 bit, how was installed (`java -version`): 
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) Client VM (build 25.311-b11, mixed mode)

 - Version of Angry IP Scanner
3.8.0

**Logs:**
- Please run Angry IP Scanner from command-line and see if any relevant logs were written. Paste them here.

Java Virtual Machine Launcher
---------------------------
Error: A JNI error has occurred, please check your installation and try again

Java Virtual Machine Launcher
---------------------------
A Java Exception has occurred.

**Comment by slaveniamh** [comment]
Seeing the same with W10Pro

**Comment by jimmisonr** [comment]
> Seeing the same with W10Pro
Same here. Rolling back to 3.7.6 got me up and running again.

**Comment by slaveniamh** [comment]
A roll back got things running here too

**Comment by jnezbeda** [comment]
Hi guys, there is solution:
`Last version to run under Java 8 is 3.7.6.`
See details [here](https://angryip.org/download/#windows).
So just update your JRE from v8 to 11.

**Comment by slaveniamh** [comment]
OK, that's it running, but it finds none of the 40ish systems on the LAN
![image](https://user-images.githubusercontent.com/6642346/149823927-62492f55-5cbf-43a0-88d8-f57d78a265f0.png)

**Comment by jnezbeda** [comment]
@slaveniamh : Yes, it is know bug, see opened #302
(Peronally I think it is about minor update JDK, not ipscan. But it is only idea, I am not sure)
Give a chance to Liberica JDK and ipscan v3.8.0- it works :-)

**Comment by angryziber** [comment]
Yes, unfortunately, Java 8 is not supported anymore, due to changes in SWT, the UI toolkit.

Some questions:
* Which vendor of Java 8 do you use? Is it AdoptOpenJDK/Oracle/something else?
  *  If it's 32-bit version, then there is a possibility to make it work
* What is the vendor of Java 11 that doesn't detect any hosts?

**Comment by epizarro2** [comment]
- Which vendor of Java 8 do you use? Is it AdoptOpenJDK/Oracle/something else?
Oracle 32 Bits, V 8 311, Changed to Last Liberica JRE and testing my other java apps. Seems fine.

**Comment by slaveniamh** [comment]
Followed the link from the download page and got-
bellsoft-jre17.0.1+12-windows-amd64.msi

**Comment by MelchiorGaspar** [comment]
I am having the same issue...
unfortunately I deleted all my backups of v3.7.x when I grabbed v3.8.2 just now..

**Comment by angryziber** [comment]
@MelchiorGaspar please try the new Windows installer than includes a minimal JRE. You don't need to install a separate Java anymore that way.

BellSoft that releases Liberica is a consultancy company founded by former engineers from Oracle, they are one of distributors of OpenJDK after Oracle made their distribution not free.

**Comment by MelchiorGaspar** [comment]
thx for the info... @angryziber  
 I will give try Liberica out... and remove the std Java RTE..
I have 2  or 3 java programs I use.. including BiglyBT...  I tried Java 11 oh years ago and BiglyBT/Azureus would not run...
 but sry I am tangenting...
 so I install v17 or v11

**Comment by angryziber** [comment]
@MelchiorGaspar latest is usually better and for running apps you need JRE (runtime environment), not JDK (which is for development). If older apps won't run, you can also keep several different versions of Java on your machine.

And again, the recommended way of running Angry IP Scanner is to use the installer that comes with a specially built minimal JRE version 11 (currently).

**Comment by MelchiorGaspar** [comment]
I am good now. I installed the full jre for Liberica  v17 and the other programs I use run with it ^_^
