### ISSUE TITLE
Windows uninstaller is not checking success

### ISSUE THREAD

**Issue by jnezbeda** [angryip/ipscan#325]
**Describe the bug**
When I have ipscan.exe opened and run unistall.exe, Uninstaller told me on the end of next-next-next Success. 
But it is wrong, when I have opened ipscan.exe, it cannot be deleted. So uninstaller is just displaying success msg, but is not checking if files were truly deleted.

**To Reproduce**
1.  open ipscan.exe
2. open uninstall.exe
3. click next-next-next
4. See success msg
5. ipscan.exe still remains

**Expected behavior**
Uninstaller must check if files were deleted.

**Versions (please complete the following information):**
 - Win 10, x64, actual
 - JDK 17, 12
 - Version of Angry IP Scanner 3.8.0

**Comment by angryziber** [comment]
What is the reason of failing to delete? Was the app running at that time?

**Comment by jnezbeda** [comment]
@angryziber : yes, app ipscan.exe was running during deletion via uninstaller.exe

**Comment by angryziber** [comment]
@jnezbeda what is the expected behavour, a GUI error message? This seems to be the default behaviour of NSIS to just skip the files it cannot delete
