### ISSUE TITLE
opt-out to Preferences dialog

### ISSUE THREAD

**Issue by jnezbeda** [angryip/ipscan#326]
**Is your feature request related to a problem? Please describe.**
Please, move checkbox "Send anonymous error reports" to Preferences dialog, where is the right place for this option. Not on Getting Started dialog (F1). It will be also nice to setup it via command line argument during installation (setup.exe /optout) or after installation set it via registry.

**Describe the solution you'd like**
I want to have this important option (checkbox) on Preferences dialog, not half hidden on Getting Started dialog (F1).

**Additional context**
Win 10, x64, ipscan v3.8.0, Liberica JDK 17.0.1, 12

**Comment by angryziber** [comment]
That's a reasonable request.
The idea of putting it in Getting Started dialog was that it's the first thing that new users see after launching the app
