### ISSUE TITLE
Skip java check (WinGet)

### ISSUE THREAD

**Issue by OfficialEsco** [angryip/ipscan#328]
**Is your feature request related to a problem? Please describe.**
Ooo, yes, when silent installing we get stuck on this window, which currently blocks it from passing winget validation.
![VirtualBoxVM_CGDhV3fNFV](https://user-images.githubusercontent.com/15158490/149909885-79320165-df4e-450a-97b9-7637c09f0014.png)

**Describe the solution you'd like**
A installer switch to skip the java check

**Describe alternatives you've considered**
null

**Additional context**

Link to our PRs: https://github.com/microsoft/winget-pkgs/pull/41077 & https://github.com/microsoft/winget-pkgs/pull/41478

**Comment by angryziber** [comment]
Have you tried installing Java first, then this check should not fail

**Comment by OfficialEsco** [comment]
Winget currently don't support dependencies (should soonMS™️)

**Comment by angryziber** [comment]
Fixed in master. The installer will now include the stripped down JRE and be totally silent.

**Comment by OfficialEsco** [comment]
Thank you 😁
