### ISSUE TITLE
v3.8.1 still not working with Java 8

### ISSUE THREAD

**Issue by pstein** [angryip/ipscan#330]
When I double click on the downloaded *.exe I am getting the following error (see attached snapshot).

Java 8 (32bit) is installed here und runs with successfully other programs

![ip scan error](https://user-images.githubusercontent.com/2775875/150292389-65af6277-f6ff-4782-ae97-3bd77b57f595.png)

**Comment by angryziber** [comment]
Sorry, that was a bad idea to try this. Windows 32-bit build removed from master and next version will bundle a minimal 64-bit JRE, so that no incompatibilities can happen anymore.
