### ISSUE TITLE
Latest Version Not Working on Linux Mint

### ISSUE THREAD

**Issue by johnwillhoward** [angryip/ipscan#333]
Describe the bug
Versions ipscan_3.8.1_amd64 and ipscan_3.8.2_amd64 do not work at all on Linux Mint 19.3

To Reproduce
Try it.

Expected behavior

Screenshots
NA

Versions (please complete the following information):

    OS version LInux Mint 19.3 cinnamon Intel core-I3 4170T CPU @ 3.2 GHz x 2

    Java version

    openjdk 10.0.1 2018-04-17
    OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
    OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

    Version of Angry IP Scanner
    8.1_amd64 OR 8.2_amd64
    Logs:
    None

**Comment by angryziber** [comment]
Please install openjdk-11 at least, 10 is no longer supported.

**Comment by johnwillhoward** [comment]
I installed openjdk-17, and all works fine now - Thank you.
