### ISSUE TITLE
Application hangs when load IPs from text file

### ISSUE THREAD

**Issue by oXydus** [angryip/ipscan#334]
**Describe the bug**
Application hangs when load IPs from text file. Version 3.7.6 is loading IPs instantly, but 3.8.2 needs 1-2 minutes for 400 IPs.

**To Reproduce**
1. Select Text File fetcher
2. Click on 'Browse' and double click text file that has IPs.
3. Wait at least 1-2 minutes to load 400 IPs. If you try to click some buttons/menus, the application is hanging.

**Expected behavior**
Instantly load IPs.

**Versions (please complete the following information):**
 - Windows 10 Pro x64
 - Java version, 32 bit
 - Version of Angry IP Scanner 3.8.2

**Comment by angryziber** [comment]
What is the format of the text file? Was it saved by Angry IP Scanner itself?
Can you share the file?

**Comment by oXydus** [comment]
It's just an txt file like this
10.10.10.1
10.10.10.2

and so on

**Comment by angryziber** [comment]
I can load a file with 1500 IP address in a blink of an eye.
Probably it would be nice if you could send your file. If you cannot share it publicly, please send it to anton at azib.net

**Comment by oXydus** [comment]
Then may be is something wrong with my software configuration. Thank you
