### ISSUE TITLE
MacOSX not starting 3.8.2 or 3.8.0

### ISSUE THREAD

**Issue by QuattroCS-Myriad** [angryip/ipscan#335]
**Describe the bug**
- Could not open new version 3.8.2 on my mac. Also tried 3.8.0. 3.7.6 is newest currently working
- Mac pro 15 2019

**To Reproduce**
- after accepting security neither version would work, except for 3.7.6

**Expected behavior**
- app bumped on taskbar but didn't open

**Screenshots**
- n/a

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner - 3.8.2 and 3.8.0
 - MacOS Catalina, 10.15.7, intel
 - java 9.0.1
 - Java(TM) SE Runtime Environment (build 9.0.1+11)
 - Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Logs:**
- no logs visible

**Comment by JonnyTech** [comment]
Java 9 is not supported, please install [JRE11](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14%2B9/OpenJDK11U-jre_x64_mac_hotspot_11.0.14_9.pkg)

**Comment by angryziber** [comment]
Please use version 3.9.0 that includes the Java Runtime
