### ISSUE TITLE
Will not open on MacOS Monterey 12.2.1

### ISSUE THREAD

**Issue by nicholasdennis** [angryip/ipscan#341]
Angry IP Scanner will not open on MacOS Monterey 12.2.1

**To Reproduce**
1. Download the latest version
2. Double click to unzip
3. Right-click on Angry IP Scanner
4. Error:
           "Anry IP Scanner” cannot be opened because the developer cannot be verified. 
           macOS cannot verify that this app is free from malware.
    
5. Go into Mac Settings -> Security & Privacy and see the following message: "“Angry IP Scanner” was blocked from use because it is not from an identified developer."

6. Click the Lock and click "Open Anyway"

7. Go back to Downloads and right-click and then Open on Angry IP Scanner. The program icon flashes in the taskbar and closes immediately.

**Expected behavior**
Program should open

**Screenshots**
<img width="666" alt="Screen Shot 2022-02-24 at 4 59 57 PM" src="https://user-images.githubusercontent.com/36744879/155614789-2f6f2c86-cd7e-4ab1-bcc5-6f064bc6a0bd.png">
<img width="260" alt="Screen Shot 2022-02-24 at 5 00 13 PM" src="https://user-images.githubusercontent.com/36744879/155614797-09d3740c-30d8-46d1-a15b-27c5f862efd6.png">

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner - 3.8.2
 - OS, version, CPU architecture - Monterey 12.2.1 and Intel 2.4 GHz 8-Core Intel Core i9
 - Java version, vendor (`java -version`) - Java 8 Update 311
 
**Logs:**
Cannot open the program to run logs.

**Comment by nicholasdennis** [comment]
Angry IP Scanner 3.8.2 and 3.8.0 will not open.

Angry IP Scanner 3.7.6 DOES work.

**Comment by JonnyTech** [comment]
Versions 3.8.* now require JRE 11, previous versions required JRE 8.

**Comment by nicholasdennis** [comment]
Installing JRE/JDK 17 worked.
