### ISSUE TITLE
JNI error in ipscan-win64-3.8.2.exe

### ISSUE THREAD

**Issue by sdel85** [angryip/ipscan#345]
**Describe the bug**
Trying to run theipscan-win64-3.8.2.exe produces a Java Virtual Machine Launcher error.

**To Reproduce**
1. Download the ipscan-win64-3.8.2.exe from this Github
2. Double-click the downloaded file
3. Error: A JNI error has occurred, please check your installation and try again.
4. See error attached.

**Expected behavior**
Application runs without an error

**Screenshots**
[JNI Error_2022-03-15_145445](https://user-images.githubusercontent.com/25733278/158461747-8dcc43fa-db2d-4130-ad54-fff4095187cd.png)

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner - 3.8.2
 - OS, version, CPU architecture - Windows 10 2H21, 64-bit
 -  java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) Client VM (build 25.321-b07, mixed mode)
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows!

**Comment by JonnyTech** [comment]
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1%2B1/OpenJDK11U-jre_x64_windows_hotspot_11.0.14.1_1.msi
