### ISSUE TITLE
"More Info" button forwards to a flash site!

### ISSUE THREAD

**Issue by DilettanteDev** [angryip/ipscan#348]
When I launched Angry IP Scanner 3.7.6 for Mac (intel) I was presented with a dialogue that read "The latest stable version is 3.8.2, but you are running 3.7.6. Would you like to open the download page now?" So I chose to download 3.8.2 and run it. But when I did, I was presented with an alert stating:

"To use the "java" command-line tool you
need to install a JDK.

Click "More Info..." to visit the Java Developer Kit
download website."

Then, when I clicked that "More Info" button? My browser launched and I was taken to an Adobe Flash site.
I noticed that it happened with version 3.8.0 as well? And I can't tell you what other versions this happens with.

Are you aware of this??  Isn't this a potential security risk?

![Screen Shot 2022-03-29 at 11 08 54 PM](https://user-images.githubusercontent.com/26414291/160684763-5c97353c-74a3-40f0-9ef0-4b4dc3a54ef0.png)
![Screen Shot 2022-03-30 at 2 35 25 AM](https://user-images.githubusercontent.com/26414291/160684773-268f44c1-5ba0-4780-9c1a-7119ab721462.png)

**Comment by angryziber** [comment]
I guess the second screen is displayed by MacOS itself.
This will be fixed by bundling Java with Mac builds.

Please test these builds here:
https://github.com/angryip/ipscan/actions/runs/3554312705
