### ISSUE TITLE
Only 3.7.3 works on intel macbook pro

### ISSUE THREAD

**Issue by cohen-erik** [angryip/ipscan#358]
**Describe the bug**
Downloaded zip, installed, and double clicked app, but it didn't work. Tried every version until 3.7.3 finally worked

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner
 - OS, version, CPU architecture
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`
  - Linux: `ipscan` or `java -jar ipscan.jar`

**Comment by lambdaupb** [comment]
For what it's worth, 3.8.2 works fine for me on monterey 12.4 with azul zulu 18.
I did have to do the open app of unknown developer dance.

**Comment by cohen-erik** [comment]
Thank you for mentioning azul zulu. This was the fix.
