### ISSUE TITLE
fail to launch 3.8.2 on OS X Monterey

### ISSUE THREAD

**Issue by haef1931** [angryip/ipscan#359]
Like the subject line says, I cannot launch 3.8.2 on OS X Monterey.

It's weird because at one point it was working.

I even tried re-downloading and reinstalling AIP.  Usual security prompts but no issues otherwise.

Suggestions?

**Comment by aleccmedina-ee** [comment]
I am currently experiencing the same issue and have not found a solution.

**Comment by casasin** [comment]
Same here.

**Comment by haef1931** [comment]
Java 17???  I'm running v8-202.  I updated to v8-333, but same problem.

I tried opening it from within the  terminal:

Tuffy-the-Spider:~ joseph$ open -a /Applications/IP\ net\ scanners\ \&\ mappers\ VARIOUS/Angry\ IP\ Scanner.app/Contents/MacOS/ipscan-macArm64-3.8.2.jar 
The application /Applications/IP net scanners & mappers VARIOUS/Angry IP Scanner.app/Contents/MacOS/ipscan-macArm64-3.8.2.jar cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003fb1110 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}


Mind you, I'm not convinced I'm doing any of this correctly.

Thanks!

**Comment by alvarnell** [comment]
Version 8 has not been sufficient for some time now. You must also install a more recent Jave JDK as outlined in this tutorial <https://java.tutorials24x7.com/blog/how-to-install-java-17-on-machttps://java.tutorials24x7.com/blog/how-to-install-java-17-on-mac>.

**Comment by angryziber** [comment]
Yep, as is stated on the download page, Java 11 is the minimum required since 3.8.0. Java 17 is recommended, as the latest long-term support release. Java 8 is way too old.

**Comment by haef1931** [comment]
Don't download Java from the obvious place.
wrong:  https://www.java.com/en/download/
good:  https://www.oracle.com/java/technologies/downloads/#jdk18-mac

That fixed it thanks.

**Comment by 3Dietrich** [comment]
+1 to the origin message
I don't want to install Java, or anything else. I want just run "Angry IP Scanner".
So I use v3.7.6 for the time being.
And I hope the big news "Happy 2022 and Mac M1 support!" becomes true also for Monterey++ :)

**Comment by IdolR** [comment]
Still not working for me, although running Java 19: https://download.oracle.com/java/19/latest/jdk-19_macos-aarch64_bin.dmg
Java seems to be ok:

> Java version "19" 2022-09-20
> Java(TM) SE Runtime Environment (build 19+36-2238)
> Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
> 

Then installed Angry Scanner M1 version https://github.com/angryip/ipscan/releases/download/3.8.2/ipscan-macArm64-3.8.2.zip

Extracted, when launched nothing happens. Running Monterey 12.6

**Comment by georgedimac** [comment]
> 

this fixed it for me, using 3.8.2 , macos m1 version on Monterey. before doing this, i was getting the Failed to load Native Code error.

**Comment by IdolR** [comment]
> Still not working for me, although running Java 19: https://download.oracle.com/java/19/latest/jdk-19_macos-aarch64_bin.dmg Java seems to be ok:
> 
> > Java version "19" 2022-09-20
> > Java(TM) SE Runtime Environment (build 19+36-2238)
> > Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
> 
> Then installed Angry Scanner M1 version https://github.com/angryip/ipscan/releases/download/3.8.2/ipscan-macArm64-3.8.2.zip
> 
> Extracted, when launched nothing happens. Running Monterey 12.6

Now working, maybe rebooting helped!

**Comment by Gabriele-LS** [comment]
> Don't download Java from the obvious place. wrong: https://www.java.com/en/download/ good: https://www.oracle.com/java/technologies/downloads/#jdk18-mac
> 
> That fixed it thanks.

Thank you. That fixed my issue too.

**Comment by angryziber** [comment]
I am trying to bundle Java runtime with Mac builds, can someone please test these here (both Intel and Arm):
https://github.com/angryip/ipscan/actions/runs/3554312705

**Comment by georgedimac** [comment]
> I am trying to bundle Java runtime with Mac builds, can someone please test these here (both Intel and Arm): https://github.com/angryip/ipscan/actions/runs/3554312705

on m1 12.6.1 does not even open. already works ok the normal version 3.8.2 - arm64

**Comment by 3Dietrich** [comment]
@georgedimac Both macOS versions do not start on my M1

**Comment by georgedimac** [comment]
this issue is about Monterey not Ventura. on Monterey there is no issue if you install jdk

**Comment by angryziber** [comment]
@georgedimac @3Dietrich thanks for trying. Could you please try also unpacking the bundle and trying to run it from Terminal?

Both `Angry IP Scanner.app/Contents/MacOS/jre/bin/java` and `Angry IP Scanner.app/Contents/MacOS/ipscan`

**Comment by georgedimac** [comment]
there is no diff between Monterey and Ventura. i tried on both, so on M1 (arm64):

latest 3.8.2 release works on on both OS if you have JDK (i tested with 19) installed.
latest build (b906c14) , on both os, does not open on double-click, but if you run the ipscan inside the folder it opens and scans perfect.

**Comment by 3Dietrich** [comment]
> @georgedimac @3Dietrich thanks for trying. Could you please try also unpacking the bundle and trying to run it from Terminal?
> 
> Both `Angry IP Scanner.app/Contents/MacOS/jre/bin/java` and `Angry IP Scanner.app/Contents/MacOS/ipscan`

@angryziber, You asked, I tried (with the arm64 part):
on M1 Ventura calling both after each other: works.

**Comment by angryziber** [comment]
I think I have fixed the launching issue now with the embedded Java.
Guys, please test these builds:
https://github.com/angryip/ipscan/actions/runs/3640355351

On both x86 and ARM CPUs

**Comment by angryziber** [comment]
@georgedimac @3Dietrich can you please try running the latest build above?

**Comment by 3Dietrich** [comment]
@angryziber YES! The arm version works on my M1. good job!

**Comment by georgedimac** [comment]
arm version works ok, but i think a better approach was to notify the user that he has to install JDK rather than to bundle it and create a larger app.

**Comment by 3Dietrich** [comment]
I find it is a GOOD approach to **include the needed Java**/JDK/? what ever the name / what ever version it needs to just run Angry Ip Scan!

**Comment by angryziber** [comment]
Version 3.9.0 released

**Comment by georgedimac** [comment]
working ok, but i have noticed that it cannot get MAC addresses , it always is shown as n/a. Can this be fixed?
