### ISSUE TITLE
ip 0 from range is not scanned

### ISSUE THREAD

**Issue by zeuz00** [angryip/ipscan#360]
**Describe the bug**
When you use an IP range that jumps from diferent segment, ip 0 is not in the list of scanned addresses.
Range 192.168.1.1-192.168.2.254  the IP 192.168.2.0 is not considered for the scanned range, which is a valid IP address

**To Reproduce**
1. ip range: 192.168.1.0 - 192.168.2.254
2. Click on 'start'
3. Scroll down all the list of scanned IP
4. IP 192.168.2.0 won't appear on the list

**Expected behavior**
IP 192.168.2.0 to appear on the list of scanned IP

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner
 Version: 3.8.2
Build date: 2022-01-22
 - OS, version, CPU architecture
 windows 11 intel i7
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java
   java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`

**Comment by nlovell** [comment]
I can replicate the issue on my machine too.

I can't quite pin down _how_ to fix it, but it looks like it's to do with how the `modifyInetAddress` method is handling the increment/decrement of each byte, around line 98.

**Comment by angryziber** [comment]
You can enable scanning .0 and .255 addresses in Preferences - turn off "Skip probably unassigned IP addresses"
