### ISSUE TITLE
Angry IP Scanner returns response information I think should be blocked

### ISSUE THREAD

**Issue by Kshaeta** [angryip/ipscan#361]
So, background, I'm using the scanner to try to see if I can access devices over a VPN, from my home, PC, to my company LAN.
I THINK there should be very limited connectivity to a few devices, based on my rules on my corporate security device.

I used Advanced IP Scanner and Angry IP Scanner, and pinging from CMD.
The results for pinging from CMD and Advanced IP Scanner are similar.  Only the few devices I have granted access to show up.

When I ping from Angry IP Scanner, it returns a list of all the PC's on my work LAN.
I do not understand how it is getting this information.
Is there a way to tell what process it used to gather this information?  I know it uses several different network probes to gather the data.

And it's obviously doing a better job of scanning, because it is finding information that is accessible.
I need to figure out how it is doing this, to block access.

Thanks,

**Comment by angryziber** [comment]
Angry IP Scanner can use several different pinging methods (selectable in Preferences).

In LAN, it will also try the ARP ping in addition, which may be the cause you are seeing your machines.
Don't worry, ARP works for local hosts only, which are on the same network.
