### ISSUE TITLE
Feature Request - Manually augmented hostname

### ISSUE THREAD

**Issue by jsimmonstx** [angryip/ipscan#367]
Feature Request:

I'd like to see the ability to manually assign host names tied to mac addresses. For instance, I have a few machines names "Raspberry Pi", and I'd like to specify "Pi-Hole #1" to it's mac address.

I visualize this name as showing up in parenthesis AFTER the name that was detected (in the Hostname column), for instance:

    [n/a] (Manually assigned name)

or

raspberrypi.local (Pi-Hole #1)

**Comment by angryziber** [comment]
Comments are designed for exactly that.
Add both MAC address and comment columns to your result list and double click on the scanned host to give it a name (as a comment)
