### ISSUE TITLE
[Feature] Add an option to settings to save path to the last file which was scanned

### ISSUE THREAD

**Issue by Dragon-0609** [angryip/ipscan#368]
**Is your feature request related to a problem? Please describe.**
I always put all IP addresses into ip.txt and scan that file. Every time selecting it isn't convenient.

**Describe the solution you'd like**
Add an option to the settings: "Save path to the last scanned text file". After that, when the program is run, it'll fill the path field automatically.

**Comment by angryziber** [comment]
You can try the command-line option `ipscan -a:file ip.txt` and even put this into a script file that you can run

**Comment by Dragon-0609** [comment]
Thanks. 
Found help, and wrote this command:

`ipscan.exe -f:file "C:\Users\Dragon\Desktop\ip.txt" -s`
