### ISSUE TITLE
I think uiu

### ISSUE THREAD

**Issue by Scamsathot** [angryip/ipscan#371]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner
 - OS, version, CPU architecture
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java
 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`
  - Linux: `ipscan` or `java -jar ipscan.jar`

**Comment by angryziber** [comment]
No information provided
