### ISSUE TITLE
Hello! I'm going to package your tool for Parrot OS. It would be great if you can create release / tag versions so I can update upstream version automatically. Something like `0.1.0` or if you want to use date, it should be like `01.02.2022`.

### ISSUE THREAD

**Issue by Scamsathot** [angryip/ipscan#372]
Hello! I'm going to package your tool for Parrot OS. It would be great if you can create release / tag versions so I can update upstream version automatically. Something like `0.1.0` or if you want to use date, it should be like `01.02.2022`.
P/s: According to #1, does this tool support checking API key that is saved in `$HOME`? IMO it should be easier for users using this tool if the configurations are saved at `$HOME/.config/`

__Originally posted by @dmknght in https://github.com/GONZOsint/geowifi/issues/2__

**Comment by angryziber** [comment]
Hi! There are releases/tag names in this repository
