### ISSUE TITLE
VPN blocking web detect

### ISSUE THREAD

**Issue by Per409** [angryip/ipscan#373]
I used Windscribe over 2 years, around the 1st of September 'web detect' stopped displaying on windows 7 and 10. After trying everything i finally emailed them - Here's the final email
 
Agustin S
Staff - 16/09/2022 4:23 PM

Hi,

 Sorry but Angry IP Scanner is a tool used for White Hat Hackers as well as Black Hat hackers. I cannot support you with such thing.

Best regards,
Agustin MS

I've change vpns but is this what the near future holds for vpns?

EDIT: Problem was in the account setting on the website - turn off streaming
delete this post if you want to

**Comment by angryziber** [comment]
Seems there is no issue here to work on
