### ISSUE TITLE
Version 3.9 and macOS: No more MAC addresses

### ISSUE THREAD

**Issue by Steffen75** [angryip/ipscan#384]
There's a problem with the version 3.9 on macOS. The column for the MAC addresses don't work anymore.  All it says is n/a for all machines that reply on the ping.

The two systems I've tested this are macOS 12.6.2 on Intel and 13.1 on Apple Silicon.

Now for the interesting part: MAC addresses do work with 3.8.2 on both systems with Eclipse Adoptium 17.0.5+8 as JRE.

Ping method is set to "Java built-in" in both versions.

**Comment by chadius616** [comment]
I am seeing the same thing.  On 3.9 both the Mac Address and Mac Vendor sections from the "fetchers" area of the preferences no longer work.  I'm guess it has something to to do with the item in the release notes that says "updated Mac vendors".  I can confirm that both of these functions work just fine in 3.8.2.  I am using the Mac intel build on a 2018 Mac Mini running Mac OS 13.1

**Comment by manolix** [comment]
Same experience here on mac M1 running macOS Ventura (13.1). I also noticed the Ping column shows 0 ms for all devices. Version: 3.8.2 works ok in my system

**Comment by ulrichloose** [comment]
The new version comes with a JRE runtime included and that causes problems. The "executable" identifiers of two files have been lost...

If you already have a Java environment, you can simply delete the entire jre folder under Angry IP Scanner.app/Contents/MacOS/jre, or give the two files the executable attribute:

chmod +x ... Angry IP Scanner.app/Contents/MacOS/jre/lib/jspawnhelper 
chmod +x ... Angry IP Scanner.app/Contents/MacOS/jre/bin/keytool

**Comment by Steffen75** [comment]
Deleting the directory of the bundeled JRE has worked for me.

**Comment by todddube** [comment]
I did what @ulrichloose noted and worked just fine now.. TY!

**Comment by manolix** [comment]
Thanks @ulrichloose <https://github.com/ulrichloose>  !! This worled for me
as well.

*---*
*Manuel González*
***@***.***

https://es.linkedin.com/in/manolix

tel: +34 912212696
mobile: +34 615036571

**Comment by angryziber** [comment]
@ulrichloose thanks for your findings!
I have excluded keytool from the bundler, and made jspawnhelper executable.

Can you guys please verify that the latest build works?
https://github.com/angryip/ipscan/actions/runs/4141816348

**Comment by todddube** [comment]
@angryziber  looks like this works - will test a couple more times today

**Comment by angryziber** [comment]
The final build should be here:
https://github.com/angryip/ipscan/actions/runs/4150883620

Will release soon as 3.9.1
