### ISSUE TITLE
Missing host name

### ISSUE THREAD

**Issue by hspindel** [angryip/ipscan#389]
Love Angry IP Scanner!!!

Using v3.9.0. One (and only one of many) hostname on my network is missing (shows [n/a]). DNS resolves the correct hostname.

Why might I be missing the one hostname? If it matters, the missing hostname belongs to a Tivo DVR. I have another Tivo on the network for which the hostname is reported correctly.

**Comment by JonnyTech** [comment]
Not enough info. What is your operating system?

**Comment by hspindel** [comment]
Win 10.  The DNS server where Angry IP resolves names is a Linux server running Bind.

Need any other info?

**Comment by angryziber** [comment]
The hostname may resolve to an IP address, but it may not resolve via reverse lookup - i.e. from IP to hostname.

You can try the reverse lookup from command-line:
`dig -x 192.168.0.25` or `nslookup 192.168.0.25`

**Comment by hspindel** [comment]
Reverse lookup works fine.

**Comment by hspindel** [comment]
Problem solved.  Missing period in my DNS reverse lookup file. :-(
