### ISSUE TITLE
Quick question!   Where are "comments" stored on an Apple Mac (OS Sonoma 14.1.1)?

### ISSUE THREAD

**Issue by Bilko67** [angryip/ipscan#431]
I am using AngryIP on a MacBook (OS Sonoma 14.1.1) and it works really well for me.

Quick question!   If I enter a "comment" where is it stored on an Apple Mac?  Is there an XML file for example containing all "comments" ?

The reason for the question is that I have entered "comments" for many devices on my network. Some of those devices are not currently visible when I do a scan - I would like to see all my "comments" and the associated MAC addresses if possible.

Many thanks in advance.

**Comment by Bilko67** [comment]
I have managed to locate the file.... So here it is for anyone else who may be interested:

Library\Preferences\com.apple.java.util.prefs.plist

**Comment by oapy123** [comment]
FYI for anyone on Windows with the same question...I don't think there is any single file where comments and preferences are stored...instead for each comment, a registry entry is created/modified in this folder: `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\ipscan\comments` .  I had 100+ devices with comments and wanted to migrate all that over to my a PC.  To do that I just navigated to `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\ipscan` and right-clicked > export and then moved that .reg file to my new PC and double-clicked it to import.  Then all my preferences and comments showed up.
