### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by 6sto** [angryip/ipscan#442]
Hi.

Here is my contribution. Please, add my Finnish translation in your application.

Inform me when new strings are added so I can update the translation file.

Regards from Finland,

- Sami '6sto' Kuusisto

PS. This has been submitted also as a feature request, but after submitting I founf out that these should be submitted as issues. **Sorry.**

FIle: [messages_fi.zip](https://github.com/angryip/ipscan/files/14719147/messages_fi.zip)

**Comment by 6sto** [comment]
This has not been added yet, I think. Hava you seen this guys?!?

Have a great weekend.

-Sami

**Comment by 6sto** [comment]
🤔

**Comment by angryziber** [comment]
Thanks!
