### ISSUE TITLE
Scan not reporting port accurately

### ISSUE THREAD

**Issue by pbudelov** [angryip/ipscan#443]
Ipscan ver. 3.9.1

Scan accurately displays Ubiquiti Unifi U6 access points' IP Address, ping time, port #, and Green icon, but Unifi Flex-HD only shows IP Address and ping time accurately, but has a purple icon and no port info (n/a).

Just an FYI...
Thx

**Comment by JonnyTech** [comment]
Then it implies that there are no open ports or web interface on those devices. No all devices have open ports, they just echo back the ping.

**Comment by pbudelov** [comment]
You are correct.  They are only accessible from the command line and the Unifi proprietary controller.

Thx

**Comment by pbudelov** [comment]
Thank you.
