### ISSUE TITLE
Bitdefender (free) detects Angry IP Scanner as PUA

### ISSUE THREAD

**Issue by IlgazC** [angryip/ipscan#463]
**Describe the bug**

Clearly not a angryipscanner bug, I noticed current installer (windows) doesn't launch because Bitdefender free version (which is quite popular) detects it as a PUA with a frightening name:

The app C:\Users\Ilgaz\Downloads\ipscan-3.9.1-setup.exe has been detected as a potentially unwanted application and was moved to quarantine.
Detection name: Application.HackTool.BEK
If you do not trust this application, you can choose to delete it.

**To Reproduce**Clearly
1. Go to '...' www.bitdefender.com
2. Install the free version
3. Download the current JVM included Windows installer of Angry IP Scanner. 

**Expected behavior**

Angry IP Scanner installed

**Screenshots**

**Versions (please copy from the About dialog or complete manually):**
 - Version of Angry IP Scanner 3.9.1 (installer sha 892405573aa34dfc49b37e4c35b655543e88ec1c5e8ffb27ab8d1bbf90fc6ae0 )
 - OS, version, CPU architecture Win 11 24H2 26100.2454
 - Java version, vendor (`java -version`) - or if Windows installer was used with bundled Java
-  **Bitdefender version build 24.0.45.220**
- 
**Logs:**
- Please run Angry IP Scanner from Terminal and see if any relevant logs were written. Paste them here:
  - Windows: `jre\bin\java -jar ipscan.exe` (inside of installation directory, e.g. C:\Program Files\Angry IP Scanner)
  - Mac: `Angry\ IP\ Scanner.app/Contents/MacOS/ipscan`
  - Linux: `ipscan` or `java -jar ipscan.jar`

PS: As they offer the AV "free", there is a very higher chance this glitch in their database will be corrected when reported by application developer. I will report as false positive as well.

**Comment by angryziber** [comment]
Please report it to them that's it's untrue.
Users need to be vocal about wrong flagging like this

**Comment by IlgazC** [comment]
> Please report it to them that's it's untrue. Users need to be vocal about wrong flagging like this

Apparently we can't be vocal about it since their "false positive submission" system doesn't seem to work. At least to this connection. Tried both Firefox and Chrome
https://www.bitdefender.co.uk/consumer/support/answer/88563/

**Comment by IlgazC** [comment]
I have received an official sounding forum reply saying it is functioning as intended, and it is a PUA in their eyes.
https://community.bitdefender.com/en/discussion/comment/347426#Comment_347426
Closing the issue.

**Comment by IlgazC** [comment]
I have received an official sounding forum reply saying it is functioning as intended, and it is a PUA in their eyes.
https://community.bitdefender.com/en/discussion/comment/347426#Comment_347426
Closing the issue.
