### ISSUE TITLE
why is it called ANGRY ip scanner

### ISSUE THREAD

**Issue by spencermacca** [angryip/ipscan#465]
**Is your feature request related to a problem? Please describe.**
can we make it happy ip scanner. it would make it more appropriate when im teaching my 6 year old daughter sysadmin tasks

**Describe the solution you'd like**
RENAME IT TO HAPPY IP SCANNER!!!

**Describe alternatives you've considered**
you could also do Chill IP Scanner or Pensive IP Scanner

**Additional context**
![image](https://github.com/user-attachments/assets/ba90df6b-08d8-4352-a715-a7f5814c97b3)

**Comment by angryziber** [comment]
Just for fun. And it also starts with "A", so gets first in some lists.
