### ISSUE TITLE
How about the arp scan?

### ISSUE THREAD

**Issue by filippogasbarro** [angryip/ipscan#51]
The arp scan is the most functional research to search host in a LAN, because there are many host that for example refuse the connection and not send any packets icmp (in response to a package tcp or udp) that the port is not open. Instead with the arp ping all hosts respond

**Comment by Orava2** [comment]
I would like to see the ARP Ping as a ping method because other ping methods are blocked by clients firewall.

**Comment by angryziber** [comment]
3.8.0 released
