### ISSUE TITLE
Mac Addresses all showing as the same.

### ISSUE THREAD

**Issue by SammMoney** [angryip/ipscan#66]
I scanned a network this morning all Mac Addresses are showing as the same address.

**Comment by angryziber** [comment]
Which OS are you using?
Can you identify the address, is it a router of yours?

**Comment by Tecnomiky** [comment]
Because We don't have new news presume that could close the issue

**Comment by FolkSong** [comment]
I'm not the original reporter but can I just ask, is this an expected limitation if you scan a subnet from outside of it? I see the same thing, every IP shows the MAC of the router. If I scan from a device within the subnet I see the real MACs.

**Comment by angryziber** [comment]
@FolkSong that really much depends on your OS, security setup, and the router.
As a rule, you can expect getting correct MAC addresses only on the local network (before any bridge/router/etc translates them).
Which OS are you using? Windows and Mac/Linux have very different implementations of getting MAC addresses.

**Comment by FolkSong** [comment]
Oh ok. I'm using Windows, and tried all the different ping methods. It's an office environment so I don't have control over the router or security settings. It's not a big deal because I can remote desktop into a PC on the subnet as needed.
