### ISSUE TITLE
Changing source nic?

### ISSUE THREAD

**Issue by cantroy** [angryip/ipscan#70]
Running this on my PC is always a chore as I have to disable all other nics in this pc, and as I have 6 virtual, a Bluetooth, VPNs, etc., It almost always takes a few extra steps.  Is there a way I can force it to always use one nic, or choose it when I run it?

**Comment by angryziber** [comment]
The easiest way is to press 'IP^' button right after start when your computer's hostname is still there, then it will offer you to choose a nic.

**Comment by angryziber** [comment]
Or you can specify the desired IP range (of your desired nic) from command-line, e.g.
`ipscan -f:range 10.0.0.0 10.1.1.1`

**Comment by Tecnomiky** [comment]
Because look like resolved presume that  could close the issue
