### ISSUE TITLE
Device Pings from terminal but does not show in app

### ISSUE THREAD

**Issue by benquan** [angryip/ipscan#79]
I have a Realand fingerprint reader that PINGs normally from Terminal but will not show when scanning IP addresses.

ping 192.168.0.90
PING 192.168.0.90 (192.168.0.90): 56 data bytes
64 bytes from 192.168.0.90: icmp_seq=0 ttl=128 time=66.446 ms
64 bytes from 192.168.0.90: icmp_seq=1 ttl=128 time=179.404 ms
64 bytes from 192.168.0.90: icmp_seq=2 ttl=128 time=27.173 ms

![ip_range_-_angry_ip_scanner](https://cloud.githubusercontent.com/assets/3030645/19964319/b36f938e-a186-11e6-8c52-8a73652ee8aa.jpg)

Any help?

**Comment by angryziber** [comment]
The "normal" ping uses ICMP echo packets. These canot be sent by non-root user on Linux or OSX.
Angry IP Scanner uses TCP and UDP packets to detect if hosts are online on these platforms.
Do you know of any ports that these devices use?

Actually, it would be nice to record the scanning process by Wireshark and then analyze the responses of these devices that we use for pinging.
