### ISSUE TITLE
OSX 10.12.2 after IP scan, nocks laptop off lan 

### ISSUE THREAD

**Issue by si458** [angryip/ipscan#84]
Hi
After I run a scan on my mmac of my local network
My laptop suddenly cant see anything network wise?
It's as if it nocks it offline?
I have to physically restart the laptop it bring it back online?
Using angry IP scanner 3.5
OSX 10.12.2
Please help
Simon

**Comment by angryziber** [comment]
Maybe you have other software that does it in case of increased traffic?
Anti-virus or something? Or it may be a hardware issue. In any case case,
ipscan should not be responsible for anything like this. All it does is
generate lots of traffic.

**Comment by si458** [comment]
My laptop is fine BEFORE I run the scanner 

It's only wen I run the scanner the laptop network just drops out???

And again cant be hardware because it's fine BEFORE I open or run the IP scanner 

Simon

**Comment by angryziber** [comment]
Theoretically, it can, because normally you don't generate so much traffic.

Please try reducing the number of threads to see if it helps to avoid the
problem.
