### ISSUE TITLE
ICMP ping not supported on MacOS 

### ISSUE THREAD

**Issue by PythonPig** [angryip/ipscan#91]
Use root privilege but it does not work.
No java library: rocksaw??  

Terminal shows:
Caused by: java.lang.RuntimeException: Unable to extract native library: rocksaw
	at net.azib.ipscan.core.LibraryLoader.loadLibrary(LibraryLoader.java:48)
	at org.savarese.rocksaw.net.RawSocket.<clinit>(RawSocket.java:82)
	... 32 more
Caused by: java.io.IOException: librocksaw.dylib not found in the jar file (classpath)
	at net.azib.ipscan.core.LibraryLoader.loadLibrary(LibraryLoader.java:34)
	... 33 more

java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

MacOS:
10.12.2 

Thanks really for this great tool.

**Comment by PythonPig** [comment]
A temporary solution to this problem.

IPSCAN doesn’t provide librocksaw.jnilib or librocksaw.dylib for ICMP PING on MacOS,so we should generate the lib manually.Additionally,for JDK1.7+,`system.mapLibraryName` returns suffix 'dylib' and not 'jnilib' ,so the lib should be librocksaw.dylib.

First:Modify the `Makefile` of rocksaw in the folder of ipscan(ext/rocksaw/src/jni) to generate librocksaw.dylib. Change jnilib to dylib on line 47 and use `make` to generate librocksaw.dylib. Copy librocksaw.dylib to ext/rocksaw/lib/.

Second:Modify build.xml in the project dir.Add `<copy file="ext/rocksaw/lib/librocksaw.dylib" todir="${bin}.mac"/>` on line 411.

Finally: `ant mac` in the project dir and the resulting binaries will be put into the dist directory. Enjoy it!

Thanks really for this great tool.

**Comment by rradillen** [comment]
With gradle this no longer works.

**Comment by angryziber** [comment]
ICMP on Mac is now possible by choosing "Java Built-In" pinger in preferences.
